-- Seed Supabase questions — généré depuis src/data/questions/
-- Supprime d'abord toutes les questions existantes
DELETE FROM questions;

-- Insère les 450 questions propres (upsert au cas où)
INSERT INTO questions (id, category, locale, difficulty, question, option_a, option_b, option_c, option_d, answer) VALUES
  ('sci-fr-easy-001', 'sciences', 'fr', 'easy', 'Quelle couleur a souvent le ciel quand il fait beau ?', 'Rouge', 'Vert', 'Bleu', 'Noir', 'C'),
  ('sci-fr-easy-002', 'sciences', 'fr', 'easy', 'Que respirons-nous pour vivre ?', 'Air', 'Eau', 'Sable', 'Lait', 'A'),
  ('sci-fr-easy-003', 'sciences', 'fr', 'easy', 'Combien de pattes a un chien ?', 'Deux', 'Quatre', 'Six', 'Huit', 'B'),
  ('sci-fr-easy-004', 'sciences', 'fr', 'easy', 'Quel animal pond des œufs ?', 'Chien', 'Chat', 'Poule', 'Cheval', 'C'),
  ('sci-fr-easy-005', 'sciences', 'fr', 'easy', 'Avec quoi voit-on ?', 'Les oreilles', 'Les yeux', 'Le nez', 'Les pieds', 'B'),
  ('sci-fr-easy-006', 'sciences', 'fr', 'easy', 'Quand l’eau gèle, elle devient quoi ?', 'Fumée', 'Jus', 'Glace', 'Sable', 'C'),
  ('sci-fr-easy-007', 'sciences', 'fr', 'easy', 'Qu’est-ce qui éclaire la Terre le jour ?', 'La Lune', 'Le Soleil', 'Une lampe', 'Une étoile filante', 'B'),
  ('sci-fr-easy-008', 'sciences', 'fr', 'easy', 'Quel fruit pousse sur un pommier ?', 'Banane', 'Orange', 'Pomme', 'Cerise', 'C'),
  ('sci-fr-easy-009', 'sciences', 'fr', 'easy', 'Quel animal est très grand et a une trompe ?', 'Éléphant', 'Chat', 'Chien', 'Lapin', 'A'),
  ('sci-fr-easy-010', 'sciences', 'fr', 'easy', 'De quoi les plantes ont-elles besoin pour boire ?', 'Huile', 'Eau', 'Lait', 'Jus', 'B'),
  ('sci-fr-easy-011', 'sciences', 'fr', 'easy', 'Quel animal donne du lait ?', 'Vache', 'Lion', 'Chien', 'Renard', 'A'),
  ('sci-fr-easy-012', 'sciences', 'fr', 'easy', 'Quel organe bat dans notre poitrine ?', 'Le cerveau', 'Le cœur', 'Le nez', 'La main', 'B'),
  ('sci-fr-easy-013', 'sciences', 'fr', 'easy', 'Quel animal a une longue trompe ?', 'Girafe', 'Éléphant', 'Chat', 'Chien', 'B'),
  ('sci-fr-easy-014', 'sciences', 'fr', 'easy', 'Quand l’eau bout, elle devient quoi ?', 'Glace', 'Jus', 'Vapeur', 'Sable', 'C'),
  ('sci-fr-easy-015', 'sciences', 'fr', 'easy', 'Quel animal miaule ?', 'Chien', 'Chat', 'Vache', 'Cheval', 'B'),
  ('sci-fr-easy-016', 'sciences', 'fr', 'easy', 'Quel animal porte une coquille sur son dos ?', 'Escargot', 'Chat', 'Chien', 'Poisson', 'A'),
  ('sci-fr-easy-017', 'sciences', 'fr', 'easy', 'Quel animal peut voler dans le ciel ?', 'Oiseau', 'Chien', 'Chat', 'Tortue', 'A'),
  ('sci-fr-easy-018', 'sciences', 'fr', 'easy', 'Quel animal vit dans l’eau et nage avec des nageoires ?', 'Chat', 'Chien', 'Poisson', 'Lapin', 'C'),
  ('sci-fr-easy-019', 'sciences', 'fr', 'easy', 'Quel animal rugit ?', 'Lion', 'Chat', 'Lapin', 'Vache', 'A'),
  ('sci-fr-easy-020', 'sciences', 'fr', 'easy', 'Quel animal a une grande crinière ?', 'Lion', 'Chien', 'Poisson', 'Lapin', 'A'),
  ('sci-fr-easy-021', 'sciences', 'fr', 'easy', 'Quel insecte fait du miel ?', 'Abeille', 'Mouche', 'Fourmi', 'Papillon', 'A'),
  ('sci-fr-easy-022', 'sciences', 'fr', 'easy', 'Quel animal a une bosse sur le dos ?', 'Chameau', 'Chat', 'Chien', 'Cheval', 'A'),
  ('sci-fr-easy-023', 'sciences', 'fr', 'easy', 'Quel animal aboie ?', 'Chat', 'Chien', 'Poisson', 'Lapin', 'B'),
  ('sci-fr-easy-024', 'sciences', 'fr', 'easy', 'Quel animal a un très long cou ?', 'Girafe', 'Chat', 'Chien', 'Poisson', 'A'),
  ('sci-fr-easy-025', 'sciences', 'fr', 'easy', 'Quel animal nage dans l’eau ?', 'Chien', 'Chat', 'Poisson', 'Vache', 'C'),
  ('sci-fr-medium-001', 'sciences', 'fr', 'medium', 'Quel organe pompe le sang ?', 'Poumon', 'Cœur', 'Estomac', 'Foie', 'B'),
  ('sci-fr-medium-002', 'sciences', 'fr', 'medium', 'Quel animal a une carapace dure ?', 'Tortue', 'Aigle', 'Dauphin', 'Renard', 'A'),
  ('sci-fr-medium-003', 'sciences', 'fr', 'medium', 'Quelle partie d''une plante fait la photosynthèse ?', 'Racine', 'Fleur', 'Feuille', 'Tige', 'C'),
  ('sci-fr-medium-004', 'sciences', 'fr', 'medium', 'Quelle planète est la plus proche du Soleil ?', 'Terre', 'Mars', 'Mercure', 'Jupiter', 'C'),
  ('sci-fr-medium-005', 'sciences', 'fr', 'medium', 'Le vent est causé par quoi ?', 'Mouvements de l''air', 'Courants marins', 'Croissance des plantes', 'Soleil éteint', 'A'),
  ('sci-fr-medium-006', 'sciences', 'fr', 'medium', 'Qu''est-ce qu''un solide qui fond devient ?', 'Gaz', 'Liquide', 'Autre solide', 'Plasma', 'B'),
  ('sci-fr-medium-007', 'sciences', 'fr', 'medium', 'Quel gaz les plantes absorbent ?', 'Oxygène', 'Azote', 'Dioxyde de carbone', 'Hydrogène', 'C'),
  ('sci-fr-medium-008', 'sciences', 'fr', 'medium', 'Quel sens utilise-t-on pour écouter ?', 'Vue', 'Ouïe', 'Goût', 'Odorat', 'B'),
  ('sci-fr-medium-009', 'sciences', 'fr', 'medium', 'Quel organe aide à respirer ?', 'Poumons', 'Cœur', 'Estomac', 'Peau', 'A'),
  ('sci-fr-medium-010', 'sciences', 'fr', 'medium', 'Quel animal pond des œufs et vole ?', 'Chien', 'Poisson', 'Oiseau', 'Chat', 'C'),
  ('sci-fr-medium-011', 'sciences', 'fr', 'medium', 'La lumière voyage plus vite que quoi ?', 'Le son', 'La pensée', 'Le vent', 'La glace', 'A'),
  ('sci-fr-medium-012', 'sciences', 'fr', 'medium', 'Quelle planète est appelée la planète rouge ?', 'Vénus', 'Mars', 'Saturne', 'Mercure', 'B'),
  ('sci-fr-medium-013', 'sciences', 'fr', 'medium', 'Quel liquide transporte les nutriments dans le corps ?', 'Lait', 'Sang', 'Urine', 'Salive', 'B'),
  ('sci-fr-medium-014', 'sciences', 'fr', 'medium', 'Quel animal est un mammifère marin ?', 'Requin', 'Dauphin', 'Pieuvre', 'Étoile de mer', 'B'),
  ('sci-fr-medium-015', 'sciences', 'fr', 'medium', 'La pluie est eau sous quelle forme ?', 'Solide', 'Gaz', 'Liquide', 'Plasma', 'C'),
  ('sci-fr-medium-016', 'sciences', 'fr', 'medium', 'Quel organe digère la nourriture ?', 'Cerveau', 'Estomac', 'Rein', 'Poumon', 'B'),
  ('sci-fr-medium-017', 'sciences', 'fr', 'medium', 'Quel phénomène cause un arc-en-ciel ?', 'Réflexion du son', 'Réfraction de la lumière', 'Magnétisme', 'Vents forts', 'B'),
  ('sci-fr-medium-018', 'sciences', 'fr', 'medium', 'Quel animal a des écailles et respire dans l''eau ?', 'Poisson', 'Chien', 'Oiseau', 'Lapin', 'A'),
  ('sci-fr-medium-019', 'sciences', 'fr', 'medium', 'Quel élément est nécessaire pour brûler ?', 'Eau', 'Air (oxygène)', 'Glaçon', 'Terre', 'B'),
  ('sci-fr-medium-020', 'sciences', 'fr', 'medium', 'Que mesure un thermomètre ?', 'Vitesse', 'Température', 'Pression', 'Distance', 'B'),
  ('sci-fr-medium-021', 'sciences', 'fr', 'medium', 'Quelle partie de la graine devient la plante ?', 'Feuille', 'Graine', 'Embryon', 'Fleur', 'C'),
  ('sci-fr-medium-022', 'sciences', 'fr', 'medium', 'Quel corps céleste éclaire la nuit sur Terre ?', 'Lune', 'Soleil', 'Mars', 'Étoile filante', 'A'),
  ('sci-fr-medium-023', 'sciences', 'fr', 'medium', 'Quelle force nous garde au sol ?', 'Frottement', 'Magnétisme', 'Gravité', 'Pression', 'C'),
  ('sci-fr-medium-024', 'sciences', 'fr', 'medium', 'Quel liquide protège la plante dans ses feuilles ?', 'Sève', 'Sang', 'Lait', 'Urine', 'A'),
  ('sci-fr-medium-025', 'sciences', 'fr', 'medium', 'Qu''est-ce qu''un habitat naturel ?', 'Maison humaine', 'Environnement d''un animal', 'Magasin', 'Bibliothèque', 'B'),
  ('sci-fr-hard-001', 'sciences', 'fr', 'hard', 'Quel système transporte l''oxygène dans le corps ?', 'Digestif', 'Circulatoire', 'Nerveux', 'Squelettique', 'B'),
  ('sci-fr-hard-002', 'sciences', 'fr', 'hard', 'Quelle classification regroupe mammifères et oiseaux ?', 'Règne', 'Ordre', 'Classe', 'Famille', 'C'),
  ('sci-fr-hard-003', 'sciences', 'fr', 'hard', 'Quel organe filtre le sang ?', 'Foie', 'Rein', 'Cœur', 'Poumon', 'B'),
  ('sci-fr-hard-004', 'sciences', 'fr', 'hard', 'Quelle partie de la fleur contient le pollen ?', 'Pistil', 'Sépale', 'Étamine', 'Tige', 'C'),
  ('sci-fr-hard-005', 'sciences', 'fr', 'hard', 'Quel est l''état d''un gaz comprimé qui devient liquide ?', 'Condensation', 'Évaporation', 'Sublimation', 'Fusion', 'A'),
  ('sci-fr-hard-006', 'sciences', 'fr', 'hard', 'Quelle planète a des anneaux visibles ?', 'Mars', 'Saturne', 'Venus', 'Mercure', 'B'),
  ('sci-fr-hard-007', 'sciences', 'fr', 'hard', 'Quel os protège le cerveau ?', 'Côtes', 'Crâne', 'Femur', 'Vertèbre', 'B'),
  ('sci-fr-hard-008', 'sciences', 'fr', 'hard', 'Quel gaz est le plus présent dans l''air ?', 'Oxygène', 'Dioxyde de carbone', 'Azote', 'Argon', 'C'),
  ('sci-fr-hard-009', 'sciences', 'fr', 'hard', 'Comment s''appelle la force entre charges opposées ?', 'Réaction', 'Attraction', 'Frottement', 'Inertie', 'B'),
  ('sci-fr-hard-010', 'sciences', 'fr', 'hard', 'Quel instrument mesure la pression atmosphérique ?', 'Thermomètre', 'Baromètre', 'Hygromètre', 'Altimètre', 'B'),
  ('sci-fr-hard-011', 'sciences', 'fr', 'hard', 'Quelle molécule est l''unité de l''ADN ?', 'Nucléotide', 'Acide aminé', 'Glucide', 'Lipide', 'A'),
  ('sci-fr-hard-012', 'sciences', 'fr', 'hard', 'Quelle est la vitesse du son approximative dans l''air ?', '340 m/s', '3 m/s', '3400 m/s', '34 m/s', 'A'),
  ('sci-fr-hard-013', 'sciences', 'fr', 'hard', 'Comment s''appelle le cycle de l''eau ?', 'Hydratation', 'Cycle hydrologique', 'Photosynthèse', 'Érosion', 'B'),
  ('sci-fr-hard-014', 'sciences', 'fr', 'hard', 'Quel type de roche vient du refroidissement du magma ?', 'Sédimentaire', 'Métamorphique', 'Ignée (magmatique)', 'Fossile', 'C'),
  ('sci-fr-hard-015', 'sciences', 'fr', 'hard', 'Quel organe produit la bile ?', 'Pancréas', 'Foie', 'Estomac', 'Vésicule biliaire', 'B'),
  ('sci-fr-hard-016', 'sciences', 'fr', 'hard', 'Quel phénomène explique les saisons ?', 'Distance variable Terre-Soleil', 'Inclinaison de l''axe terrestre', 'Activité solaire uniquement', 'Lune proche', 'B'),
  ('sci-fr-hard-017', 'sciences', 'fr', 'hard', 'Quel ion donne une solution acide ?', 'H+', 'OH-', 'Na+', 'Cl-', 'A'),
  ('sci-fr-hard-018', 'sciences', 'fr', 'hard', 'Quel terme décrit la variation héréditaire ?', 'Mutation', 'Évaporation', 'Photosynthèse', 'Condensation', 'A'),
  ('sci-fr-hard-019', 'sciences', 'fr', 'hard', 'Quel organe réagit aux signaux et contrôle le corps ?', 'Poumon', 'Cerveau', 'Cœur', 'Rein', 'B'),
  ('sci-fr-hard-020', 'sciences', 'fr', 'hard', 'Comment s''appelle la transformation solide → gaz sans liquide ?', 'Fusion', 'Sublimation', 'Condensation', 'Évaporation', 'B'),
  ('sci-fr-hard-021', 'sciences', 'fr', 'hard', 'Quel type d''énergie produit une éolienne ?', 'Thermique', 'Chimique', 'Électrique via énergie mécanique', 'Nulle', 'C'),
  ('sci-fr-hard-022', 'sciences', 'fr', 'hard', 'Quel nombre décrit la masse d''un atome principalement ?', 'Nombre d''électrons', 'Nombre de protons', 'Nombre de nucléons (protons+neutrons)', 'Nombre de molécules', 'C'),
  ('sci-fr-hard-023', 'sciences', 'fr', 'hard', 'Quel organe stocke l''urine avant évacuation ?', 'Vessie', 'Foie', 'Estomac', 'Rein', 'A'),
  ('sci-fr-hard-024', 'sciences', 'fr', 'hard', 'Quelle couche protège la Terre des météores ?', 'Lithosphère', 'Troposphère', 'Mésosphère', 'Thermosphère', 'C'),
  ('sci-fr-hard-025', 'sciences', 'fr', 'hard', 'Quel élément forme l''eau avec l''oxygène ?', 'Carbone', 'Hydrogène', 'Azote', 'Calcium', 'B'),
  ('sci-en-easy-001', 'sciences', 'en', 'easy', 'Which planet is closest to the Sun?', 'Venus', 'Mars', 'Mercury', 'Earth', 'C'),
  ('sci-en-easy-002', 'sciences', 'en', 'easy', 'Which gas do we mainly breathe to live?', 'Oxygen', 'Hydrogen', 'Carbon', 'Nitrogen', 'A'),
  ('sci-en-easy-003', 'sciences', 'en', 'easy', 'How many legs does a spider have?', 'Six', 'Eight', 'Ten', 'Four', 'B'),
  ('sci-en-easy-004', 'sciences', 'en', 'easy', 'Which animal lays eggs?', 'Dog', 'Cat', 'Chicken', 'Horse', 'C'),
  ('sci-en-easy-005', 'sciences', 'en', 'easy', 'Which part of the body allows us to see?', 'Ears', 'Eyes', 'Mouth', 'Hands', 'B'),
  ('sci-en-easy-006', 'sciences', 'en', 'easy', 'What is the state of water when it freezes?', 'Gas', 'Liquid', 'Solid', 'Steam', 'C'),
  ('sci-en-easy-007', 'sciences', 'en', 'easy', 'Which star lights up the Earth during the day?', 'The Moon', 'The Sun', 'The stars', 'Mars', 'B'),
  ('sci-en-easy-008', 'sciences', 'en', 'easy', 'Which fruit grows on an apple tree?', 'Pear', 'Orange', 'Apple', 'Banana', 'C'),
  ('sci-en-easy-009', 'sciences', 'en', 'easy', 'What is the largest land animal?', 'Elephant', 'Giraffe', 'Rhinoceros', 'Hippopotamus', 'A'),
  ('sci-en-easy-010', 'sciences', 'en', 'easy', 'What liquid do plants absorb through their roots?', 'Juice', 'Water', 'Oil', 'Milk', 'B'),
  ('sci-en-easy-011', 'sciences', 'en', 'easy', 'Which animal gives milk?', 'Cow', 'Horse', 'Dog', 'Rabbit', 'A'),
  ('sci-en-easy-012', 'sciences', 'en', 'easy', 'Which organ pumps blood in our body?', 'The brain', 'The heart', 'The lungs', 'The stomach', 'B'),
  ('sci-en-easy-013', 'sciences', 'en', 'easy', 'Which animal has a long trunk?', 'Giraffe', 'Elephant', 'Lion', 'Zebra', 'B'),
  ('sci-en-easy-014', 'sciences', 'en', 'easy', 'What is the state of water when it boils?', 'Solid', 'Liquid', 'Gas', 'Ice', 'C'),
  ('sci-en-easy-015', 'sciences', 'en', 'easy', 'Which animal meows?', 'Dog', 'Cat', 'Bird', 'Horse', 'B'),
  ('sci-en-easy-016', 'sciences', 'en', 'easy', 'Which animal has a shell?', 'Snail', 'Fish', 'Dog', 'Cat', 'A'),
  ('sci-en-easy-017', 'sciences', 'en', 'easy', 'Which animal can fly?', 'Bird', 'Dog', 'Cat', 'Rabbit', 'A'),
  ('sci-en-easy-018', 'sciences', 'en', 'easy', 'Which animal lives in water and has fins?', 'Dog', 'Cat', 'Fish', 'Horse', 'C'),
  ('sci-en-easy-019', 'sciences', 'en', 'easy', 'Which animal roars?', 'Lion', 'Cat', 'Dog', 'Bird', 'A'),
  ('sci-en-easy-020', 'sciences', 'en', 'easy', 'Which animal has a mane?', 'Lion', 'Elephant', 'Giraffe', 'Zebra', 'A'),
  ('sci-en-easy-021', 'sciences', 'en', 'easy', 'Which animal makes honey?', 'Bee', 'Butterfly', 'Fly', 'Ant', 'A'),
  ('sci-en-easy-022', 'sciences', 'en', 'easy', 'Which animal has a hump?', 'Camel', 'Horse', 'Cow', 'Zebra', 'A'),
  ('sci-en-easy-023', 'sciences', 'en', 'easy', 'Which animal barks?', 'Cat', 'Dog', 'Bird', 'Rabbit', 'B'),
  ('sci-en-easy-024', 'sciences', 'en', 'easy', 'Which animal lives in the savannah and has a long neck?', 'Giraffe', 'Lion', 'Elephant', 'Zebra', 'A'),
  ('sci-en-easy-025', 'sciences', 'en', 'easy', 'Which animal can swim and has fins?', 'Dog', 'Cat', 'Fish', 'Rabbit', 'C'),
  ('sci-en-medium-001', 'sciences', 'en', 'medium', 'How many planets are in the solar system?', 'Seven', 'Eight', 'Nine', 'Ten', 'B'),
  ('sci-en-medium-002', 'sciences', 'en', 'medium', 'Which organ controls the whole body?', 'The heart', 'The brain', 'The lungs', 'The stomach', 'B'),
  ('sci-en-medium-003', 'sciences', 'en', 'medium', 'Which gas do plants release during photosynthesis?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen', 'A'),
  ('sci-en-medium-004', 'sciences', 'en', 'medium', 'Which is the fastest land animal?', 'Lion', 'Cheetah', 'Horse', 'Tiger', 'B'),
  ('sci-en-medium-005', 'sciences', 'en', 'medium', 'Which is the largest ocean in the world?', 'Atlantic', 'Pacific', 'Indian', 'Arctic', 'B'),
  ('sci-en-medium-006', 'sciences', 'en', 'medium', 'Which metal is used to make soda cans?', 'Iron', 'Aluminum', 'Copper', 'Zinc', 'B'),
  ('sci-en-medium-007', 'sciences', 'en', 'medium', 'Which is the largest marine animal?', 'Great white shark', 'Blue whale', 'Orca', 'Dolphin', 'B'),
  ('sci-en-medium-008', 'sciences', 'en', 'medium', 'Which celestial body orbits the Earth?', 'The Sun', 'The Moon', 'Mars', 'Venus', 'B'),
  ('sci-en-medium-009', 'sciences', 'en', 'medium', 'Which animal can change its color to camouflage?', 'Chameleon', 'Zebra', 'Lion', 'Giraffe', 'A'),
  ('sci-en-medium-010', 'sciences', 'en', 'medium', 'Which organ allows us to breathe?', 'The heart', 'The lungs', 'The liver', 'The stomach', 'B'),
  ('sci-en-medium-011', 'sciences', 'en', 'medium', 'Which sea animal has tentacles?', 'Jellyfish', 'Fish', 'Crab', 'Turtle', 'A'),
  ('sci-en-medium-012', 'sciences', 'en', 'medium', 'Which is the smallest bone in the human body?', 'Femur', 'Stapes', 'Tibia', 'Clavicle', 'B'),
  ('sci-en-medium-013', 'sciences', 'en', 'medium', 'Which animals live in polar regions and eat fish?', 'Penguin', 'Polar bear', 'Seal', 'All three', 'D'),
  ('sci-en-medium-014', 'sciences', 'en', 'medium', 'Which star is at the center of the solar system?', 'Earth', 'The Sun', 'The Moon', 'Mars', 'B'),
  ('sci-en-medium-015', 'sciences', 'en', 'medium', 'Which animal has a pouch for its babies?', 'Kangaroo', 'Lion', 'Giraffe', 'Dog', 'A'),
  ('sci-en-medium-016', 'sciences', 'en', 'medium', 'Which is the largest desert in the world?', 'Sahara', 'Gobi', 'Kalahari', 'Atacama', 'A'),
  ('sci-en-medium-017', 'sciences', 'en', 'medium', 'Which animal has feathers and lays eggs?', 'Bird', 'Dog', 'Cat', 'Rabbit', 'A'),
  ('sci-en-medium-018', 'sciences', 'en', 'medium', 'Which sea animal has a shell?', 'Snail', 'Oyster', 'Crab', 'Jellyfish', 'B'),
  ('sci-en-medium-019', 'sciences', 'en', 'medium', 'Which animal flies at night and uses echolocation?', 'Bat', 'Bird', 'Butterfly', 'Fly', 'A'),
  ('sci-en-medium-020', 'sciences', 'en', 'medium', 'Which sea animal has eight arms?', 'Crab', 'Octopus', 'Jellyfish', 'Fish', 'B'),
  ('sci-en-medium-021', 'sciences', 'en', 'medium', 'Which animal can live without water for a long time?', 'Camel', 'Horse', 'Cow', 'Zebra', 'A'),
  ('sci-en-medium-022', 'sciences', 'en', 'medium', 'Which animal has a hard shell?', 'Turtle', 'Fish', 'Dog', 'Cat', 'A'),
  ('sci-en-medium-023', 'sciences', 'en', 'medium', 'Which animal can live both on land and in water?', 'Frog', 'Dog', 'Cat', 'Bird', 'A'),
  ('sci-en-medium-024', 'sciences', 'en', 'medium', 'Which animal has a trunk and big ears?', 'Elephant', 'Giraffe', 'Lion', 'Zebra', 'A'),
  ('sci-en-medium-025', 'sciences', 'en', 'medium', 'Which animal lives in the ocean and breathes through gills?', 'Dog', 'Cat', 'Fish', 'Rabbit', 'C'),
  ('sci-en-hard-001', 'sciences', 'en', 'hard', 'Which chemical element has the symbol Fe?', 'Iron', 'Fluorine', 'Francium', 'Fermium', 'A'),
  ('sci-en-hard-002', 'sciences', 'en', 'hard', 'What is the largest organ in the human body?', 'The liver', 'The skin', 'The heart', 'The lungs', 'B'),
  ('sci-en-hard-003', 'sciences', 'en', 'hard', 'Which celestial body is closest to Earth after the Moon?', 'Mars', 'Venus', 'The Sun', 'Jupiter', 'B'),
  ('sci-en-hard-004', 'sciences', 'en', 'hard', 'Which gas is most abundant in Earth''s atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen', 'B'),
  ('sci-en-hard-005', 'sciences', 'en', 'hard', 'Which scientist discovered the law of universal gravitation?', 'Galileo', 'Newton', 'Einstein', 'Copernicus', 'B'),
  ('sci-en-hard-006', 'sciences', 'en', 'hard', 'Which organ produces insulin?', 'The liver', 'The pancreas', 'The kidneys', 'The stomach', 'B'),
  ('sci-en-hard-007', 'sciences', 'en', 'hard', 'Which ocean animal is considered the most intelligent?', 'Dolphin', 'Octopus', 'Orca', 'Seal', 'A'),
  ('sci-en-hard-008', 'sciences', 'en', 'hard', 'What is the scientific name for water?', 'H2O', 'CO2', 'NaCl', 'O2', 'A'),
  ('sci-en-hard-009', 'sciences', 'en', 'hard', 'Which is the longest bone in the human body?', 'Femur', 'Tibia', 'Humerus', 'Clavicle', 'A'),
  ('sci-en-hard-010', 'sciences', 'en', 'hard', 'Which animal can regenerate its limbs?', 'Starfish', 'Frog', 'Dog', 'Cat', 'A'),
  ('sci-en-hard-011', 'sciences', 'en', 'hard', 'What is the name of the galaxy where Earth is located?', 'Andromeda', 'Milky Way', 'Sagittarius', 'Orion', 'B'),
  ('sci-en-hard-012', 'sciences', 'en', 'hard', 'Which animal has three hearts?', 'Octopus', 'Dolphin', 'Shark', 'Turtle', 'A'),
  ('sci-en-hard-013', 'sciences', 'en', 'hard', 'What is the name of Earth''s natural satellite?', 'Mars', 'The Moon', 'Io', 'Titan', 'B'),
  ('sci-en-hard-014', 'sciences', 'en', 'hard', 'Which is the smallest planet in the solar system?', 'Mars', 'Mercury', 'Pluto', 'Venus', 'B'),
  ('sci-en-hard-015', 'sciences', 'en', 'hard', 'What is the process by which plants make their food?', 'Respiration', 'Photosynthesis', 'Digestion', 'Fermentation', 'B'),
  ('sci-en-hard-016', 'sciences', 'en', 'hard', 'Which animal can live without its head for several days?', 'Cockroach', 'Frog', 'Fish', 'Snail', 'A'),
  ('sci-en-hard-017', 'sciences', 'en', 'hard', 'What is the name of the air layer that protects Earth from the Sun''s rays?', 'Troposphere', 'Ozone', 'Stratosphere', 'Atmosphere', 'B'),
  ('sci-en-hard-018', 'sciences', 'en', 'hard', 'What is the name of the closest star to Earth after the Sun?', 'Sirius', 'Proxima Centauri', 'Polaris', 'Vega', 'B'),
  ('sci-en-hard-019', 'sciences', 'en', 'hard', 'Which animal can produce electricity?', 'Electric eel', 'Shark', 'Dolphin', 'Jellyfish', 'A'),
  ('sci-en-hard-020', 'sciences', 'en', 'hard', 'Which is the largest active volcano in the world?', 'Etna', 'Mauna Loa', 'Krakatoa', 'Vesuvius', 'B'),
  ('sci-en-hard-021', 'sciences', 'en', 'hard', 'Which planet is known for its rings?', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'B'),
  ('sci-en-hard-022', 'sciences', 'en', 'hard', 'Which organism can live in hot springs?', 'Thermophilic bacteria', 'Frog', 'Fish', 'Snail', 'A'),
  ('sci-en-hard-023', 'sciences', 'en', 'hard', 'Which animal can survive in space for some time?', 'Tardigrade', 'Ant', 'Frog', 'Snail', 'A'),
  ('sci-en-hard-024', 'sciences', 'en', 'hard', 'Which is the largest planet in the solar system?', 'Saturn', 'Jupiter', 'Neptune', 'Uranus', 'B'),
  ('sci-en-hard-025', 'sciences', 'en', 'hard', 'What is the phenomenon that creates a multicolored arc in the sky after rain?', 'Eclipse', 'Rainbow', 'Storm', 'Aurora Borealis', 'B'),
  ('hist-fr-001', 'histoire', 'fr', 'hard', 'Qui était le chef de l''Allemagne nazie pendant la Seconde Guerre mondiale ?', 'Mussolini', 'Franco', 'Hitler', 'Staline', 'C'),
  ('hist-fr-002', 'histoire', 'fr', 'medium', 'Quel pharaon est associé à la grande pyramide de Gizeh ?', 'Ramsès II', 'Khéops', 'Akhenaton', 'Toutankhamon', 'B'),
  ('hist-fr-003', 'histoire', 'fr', 'easy', 'Qui était le premier président des États-Unis ?', 'Abraham Lincoln', 'Thomas Jefferson', 'George Washington', 'Benjamin Franklin', 'C'),
  ('hist-fr-004', 'histoire', 'fr', 'medium', 'Quel empire était dirigé par Jules César ?', 'L''Empire grec', 'L''Empire romain', 'L''Empire perse', 'L''Empire égyptien', 'B'),
  ('hist-fr-008', 'histoire', 'fr', 'easy', 'Quel traité a mis fin à la Première Guerre mondiale ?', 'Traité de Paris', 'Traité d''Utrecht', 'Traité de Versailles', 'Traité de Westphalie', 'C'),
  ('hist-fr-010', 'histoire', 'fr', 'hard', 'Qui était le leader de l''Union soviétique pendant la crise des missiles de Cuba ?', 'Staline', 'Brejnev', 'Gorbatchev', 'Khrouchtchev', 'D'),
  ('hist-fr-013', 'histoire', 'fr', 'hard', 'Qui a découvert l''Amérique en 1492 ?', 'Amerigo Vespucci', 'Vasco de Gama', 'Magellan', 'Christophe Colomb', 'D'),
  ('hist-fr-018', 'histoire', 'fr', 'medium', 'Qui était le premier empereur de Rome ?', 'Jules César', 'Néron', 'Auguste', 'Tibère', 'C'),
  ('hist-fr-020', 'histoire', 'fr', 'easy', 'Quel mur est tombé en 1989 ?', 'La Grande Muraille', 'Le mur de Berlin', 'Le mur d''Hadrien', 'Le mur de Chine', 'B'),
  ('hist-fr-037', 'histoire', 'fr', 'medium', 'En quelle année la Révolution française a-t-elle commencé ?', '1776', '1783', '1789', '1793', 'C'),
  ('hist-fr-101', 'histoire', 'fr', 'easy', 'Quel monument célèbre se trouve en Égypte ?', 'Le Colisée', 'Les pyramides', 'Le Parthénon', 'La Tour Eiffel', 'B'),
  ('hist-fr-102', 'histoire', 'fr', 'easy', 'Comment s''appelle l''écriture des anciens Égyptiens ?', 'Les runes', 'Le cunéiforme', 'L''alphabet', 'Les hiéroglyphes', 'D'),
  ('hist-fr-103', 'histoire', 'fr', 'easy', 'Quel peuple a construit le Colisée à Rome ?', 'Les Grecs', 'Les Gaulois', 'Les Romains', 'Les Égyptiens', 'C'),
  ('hist-fr-104', 'histoire', 'fr', 'easy', 'Comment s''appellent les bateaux des Vikings ?', 'Les galères', 'Les caravelles', 'Les jonques', 'Les drakkars', 'D'),
  ('hist-fr-105', 'histoire', 'fr', 'easy', 'Quel roi a fait construire le château de Versailles ?', 'Napoléon', 'Louis XVI', 'Louis XIV', 'Henri IV', 'C'),
  ('hist-fr-106', 'histoire', 'fr', 'easy', 'En quelle année a commencé la Première Guerre mondiale ?', '1904', '1914', '1924', '1939', 'B'),
  ('hist-fr-107', 'histoire', 'fr', 'easy', 'Qui a marché sur la Lune en premier ?', 'Buzz Aldrin', 'Yuri Gagarine', 'John Glenn', 'Neil Armstrong', 'D'),
  ('hist-fr-108', 'histoire', 'fr', 'easy', 'Quelle ville a été détruite par le volcan Vésuve en 79 après J.-C. ?', 'Naples', 'Rome', 'Pompéi', 'Carthage', 'C'),
  ('hist-fr-109', 'histoire', 'fr', 'easy', 'Quel animal Hannibal a-t-il utilisé pour traverser les Alpes ?', 'Des chevaux', 'Des chameaux', 'Des éléphants', 'Des ânes', 'C'),
  ('hist-fr-110', 'histoire', 'fr', 'easy', 'Qui était le roi des dieux dans la mythologie grecque ?', 'Poséidon', 'Arès', 'Apollon', 'Zeus', 'D'),
  ('hist-fr-111', 'histoire', 'fr', 'easy', 'Quel explorateur a réalisé le premier tour du monde ?', 'Colomb', 'Vasco de Gama', 'Magellan', 'Cartier', 'C'),
  ('hist-fr-112', 'histoire', 'fr', 'easy', 'Qui était le roi des Francs couronné en l''an 800 ?', 'Clovis', 'Pépin', 'Charlemagne', 'Charles Martel', 'C'),
  ('hist-fr-113', 'histoire', 'fr', 'easy', 'En quelle année la Seconde Guerre mondiale a-t-elle pris fin ?', '1943', '1944', '1946', '1945', 'D'),
  ('hist-fr-114', 'histoire', 'fr', 'easy', 'Quel pays a construit la Grande Muraille ?', 'Le Japon', 'La Mongolie', 'La Chine', 'L''Inde', 'C'),
  ('hist-fr-115', 'histoire', 'fr', 'easy', 'Qui était le chef des Gaulois contre Jules César ?', 'Astérix', 'Ambiorix', 'Brennus', 'Vercingétorix', 'D'),
  ('hist-fr-116', 'histoire', 'fr', 'easy', 'Quel roi de France était surnommé le Roi-Soleil ?', 'Louis XIII', 'Henri IV', 'François I', 'Louis XIV', 'D'),
  ('hist-fr-117', 'histoire', 'fr', 'easy', 'Où les anciens Grecs organisaient-ils les premiers Jeux olympiques ?', 'À Athènes', 'À Sparte', 'À Olympie', 'À Corinthe', 'C'),
  ('hist-fr-118', 'histoire', 'fr', 'easy', 'Qui était le premier homme à voyager dans l''espace ?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarine', 'John Glenn', 'C'),
  ('hist-fr-119', 'histoire', 'fr', 'easy', 'Quel peuple vivait en Mésopotamie et a inventé l''écriture ?', 'Les Égyptiens', 'Les Perses', 'Les Babyloniens', 'Les Sumériens', 'D'),
  ('hist-fr-120', 'histoire', 'fr', 'easy', 'Qui a inventé l''imprimerie en Europe au 15e siècle ?', 'Léonard de Vinci', 'Gutenberg', 'Copernic', 'Galilée', 'B'),
  ('hist-fr-121', 'histoire', 'fr', 'easy', 'Quel peuple a inventé la démocratie dans l''Antiquité ?', 'Les Romains', 'Les Perses', 'Les Grecs', 'Les Égyptiens', 'C'),
  ('hist-fr-122', 'histoire', 'fr', 'easy', 'Comment s''appelait la guerrière française qui a aidé à libérer Orléans ?', 'Marie-Antoinette', 'Jeanne d''Arc', 'Aliénor d''Aquitaine', 'Isabelle de France', 'B'),
  ('hist-fr-201', 'histoire', 'fr', 'medium', 'Quelle civilisation a construit Machu Picchu ?', 'Les Aztèques', 'Les Mayas', 'Les Incas', 'Les Olmèques', 'C'),
  ('hist-fr-202', 'histoire', 'fr', 'medium', 'En quelle année l''Empire ottoman a-t-il conquis Constantinople ?', '1389', '1415', '1453', '1492', 'C'),
  ('hist-fr-203', 'histoire', 'fr', 'medium', 'Qui a fondé l''Empire mongol au 13e siècle ?', 'Tamerlan', 'Kubilai Khan', 'Attila', 'Gengis Khan', 'D'),
  ('hist-fr-204', 'histoire', 'fr', 'medium', 'Quel document Magna Carta a-t-il été signé en 1215 ?', 'En France', 'En Italie', 'En Angleterre', 'En Espagne', 'C'),
  ('hist-fr-205', 'histoire', 'fr', 'medium', 'Qui était le premier dirigeant de l''URSS ?', 'Trotski', 'Staline', 'Khrouchtchev', 'Lénine', 'D'),
  ('hist-fr-206', 'histoire', 'fr', 'medium', 'Quel conquistador a conquis l''Empire aztèque ?', 'Francisco Pizarro', 'Hernán Cortés', 'Vasco de Gama', 'Amerigo Vespucci', 'B'),
  ('hist-fr-207', 'histoire', 'fr', 'medium', 'Quelle civilisation antique a inventé la démocratie représentative ?', 'Rome', 'Athènes', 'Carthage', 'Babylone', 'B'),
  ('hist-fr-208', 'histoire', 'fr', 'medium', 'Quel roi d''Angleterre a fondé l''Église anglicane ?', 'Richard I', 'Edward VI', 'Henri VIII', 'James I', 'C'),
  ('hist-fr-209', 'histoire', 'fr', 'medium', 'Quel empire a été renversé par Alexandre le Grand ?', 'L''Empire romain', 'L''Empire babylonien', 'L''Empire égyptien', 'L''Empire perse', 'D'),
  ('hist-fr-210', 'histoire', 'fr', 'medium', 'En quelle année Napoléon est-il devenu emperor de France ?', '1799', '1801', '1804', '1807', 'C'),
  ('hist-fr-211', 'histoire', 'fr', 'medium', 'Quelle alliance militaire a été créée par les pays occidentaux en 1949 ?', 'L''ONU', 'Le Pacte de Varsovie', 'L''URSS', 'L''OTAN', 'D'),
  ('hist-fr-212', 'histoire', 'fr', 'medium', 'Quel navigateur portugais a découvert la route maritime vers l''Inde ?', 'Bartolomeu Dias', 'Christophe Colomb', 'Vasco de Gama', 'Pedro Álvares Cabral', 'C'),
  ('hist-fr-213', 'histoire', 'fr', 'medium', 'Quelle ville antique était la grande rivale de Rome en Méditerranée ?', 'Athènes', 'Alexandrie', 'Carthage', 'Corinthe', 'C'),
  ('hist-fr-214', 'histoire', 'fr', 'medium', 'En quelle année la Seconde Guerre mondiale a-t-elle commencé ?', '1937', '1938', '1940', '1939', 'D'),
  ('hist-fr-215', 'histoire', 'fr', 'medium', 'Quel événement a déclenché la Première Guerre mondiale ?', 'L''invasion de la Pologne', 'La révolution russe', 'L''assassinat de l''archiduc François-Ferdinand', 'L''annexion de l''Alsace', 'C'),
  ('hist-fr-216', 'histoire', 'fr', 'medium', 'Quel pharaon est connu pour avoir imposé le culte d''un seul dieu en Égypte ?', 'Ramsès II', 'Akhenaton', 'Toutankhamon', 'Thoutmosis', 'B'),
  ('hist-fr-217', 'histoire', 'fr', 'medium', 'Quelle révolution a renversé le tsar Nicolas II de Russie ?', 'La Révolution américaine', 'La Révolution française', 'La Révolution russe', 'La Révolution industrielle', 'C'),
  ('hist-fr-218', 'histoire', 'fr', 'medium', 'Combien d''années a duré la Guerre de Cent Ans entre la France et l''Angleterre ?', 'Environ 50 ans', 'Environ 75 ans', 'Environ 100 ans', 'Environ 116 ans', 'D'),
  ('hist-fr-219', 'histoire', 'fr', 'medium', 'Quel traité a mis fin aux guerres napoléoniennes en 1815 ?', 'Le Traité de Westphalie', 'Le Congrès de Vienne', 'Le Traité d''Utrecht', 'Le Traité de Versailles', 'B'),
  ('hist-fr-220', 'histoire', 'fr', 'medium', 'Quel conquistador a conquis l''Empire inca ?', 'Hernán Cortés', 'Vasco de Gama', 'Francisco Pizarro', 'Juan Ponce de León', 'C'),
  ('hist-fr-221', 'histoire', 'fr', 'medium', 'Quel peuple a fondé Carthage en Afrique du Nord ?', 'Les Grecs', 'Les Phéniciens', 'Les Romains', 'Les Berbères', 'B'),
  ('hist-fr-301', 'histoire', 'fr', 'hard', 'Qui a écrit La Guerre des Gaules, récit de ses conquêtes militaires ?', 'Cicéron', 'Tacite', 'Virgile', 'Jules César', 'D'),
  ('hist-fr-302', 'histoire', 'fr', 'hard', 'Quel traité a mis fin à la Guerre de Trente Ans en 1648 ?', 'Traité d''Utrecht', 'Traité de Paris', 'Traité de Westphalie', 'Traité de Vienne', 'C'),
  ('hist-fr-303', 'histoire', 'fr', 'hard', 'Quelle bataille en 732 a stoppé l''avancée des Maures en France ?', 'Bataille de Verdun', 'Bataille de Poitiers', 'Bataille d''Alésia', 'Bataille de Marignan', 'B'),
  ('hist-fr-304', 'histoire', 'fr', 'hard', 'Quelle reine d''Égypte était alliée à Jules César puis à Marc Antoine ?', 'Néfertiti', 'Hatchepsout', 'Nefertari', 'Cléopâtre', 'D'),
  ('hist-fr-305', 'histoire', 'fr', 'hard', 'Quel philosophe grec était le maître d''Alexandre le Grand ?', 'Platon', 'Socrate', 'Aristote', 'Pythagore', 'C'),
  ('hist-fr-306', 'histoire', 'fr', 'hard', 'En quelle année Louis XVI a-t-il été guillotiné pendant la Révolution française ?', '1791', '1792', '1793', '1795', 'C'),
  ('hist-fr-307', 'histoire', 'fr', 'hard', 'Quel est le nom de la bataille où Napoléon a été définitivement vaincu en 1815 ?', 'Austerlitz', 'Borodino', 'Waterloo', 'Leipzig', 'C'),
  ('hist-fr-308', 'histoire', 'fr', 'hard', 'Quel emperor romain a adopté le christianisme comme religion officielle de l''Empire ?', 'Auguste', 'Tibère', 'Dioclétien', 'Constantin', 'D'),
  ('hist-fr-309', 'histoire', 'fr', 'hard', 'Quel empire africain était connu pour sa richesse et son roi Mansa Moussa au 14e siècle ?', 'L''Empire du Ghana', 'L''Empire du Mali', 'L''Empire Songhaï', 'L''Empire du Zimbabwe', 'B'),
  ('hist-fr-310', 'histoire', 'fr', 'hard', 'En quelle année la chute de l''Empire romain d''Occident est-elle datée ?', '370 apr. J.-C.', '410 apr. J.-C.', '476 apr. J.-C.', '527 apr. J.-C.', 'C'),
  ('hist-fr-311', 'histoire', 'fr', 'hard', 'Quel chef viking a fondé le duché de Normandie au 10e siècle ?', 'Ragnar Lothbrok', 'Erik le Rouge', 'Leif Erikson', 'Rollon', 'D'),
  ('hist-fr-312', 'histoire', 'fr', 'hard', 'Quel empire a été fondé par Cyrus le Grand au 6e siècle avant J.-C. ?', 'L''Empire babylonien', 'L''Empire mède', 'L''Empire perse', 'L''Empire assyrien', 'C'),
  ('hist-fr-313', 'histoire', 'fr', 'hard', 'Quel plan américain a aidé à reconstruire l''Europe après la Seconde Guerre mondiale ?', 'Le Plan Dawes', 'Le Plan Schuman', 'Le New Deal', 'Le Plan Marshall', 'D'),
  ('hist-fr-314', 'histoire', 'fr', 'hard', 'Qui a écrit L''Art de la guerre, traité militaire chinois ?', 'Confucius', 'Lao Tseu', 'Sun Tzu', 'Mao Zedong', 'C'),
  ('hist-fr-315', 'histoire', 'fr', 'hard', 'Quel pays a lancé le premier satellite artificiel Spoutnik en 1957 ?', 'Les États-Unis', 'La France', 'L''Allemagne', 'L''URSS', 'D'),
  ('hist-fr-316', 'histoire', 'fr', 'hard', 'Quel pharaon est souvent associé à l''Exode des Hébreux selon la Bible ?', 'Amenhotep III', 'Akhenaton', 'Ramsès II', 'Thoutmosis III', 'C'),
  ('hist-fr-317', 'histoire', 'fr', 'hard', 'Quelle bataille oppose Athènes à Sparte de 431 à 404 avant J.-C. ?', 'La Guerre du Péloponnèse', 'Les Guerres médiques', 'La Guerre de Troie', 'La Guerre de Corinthe', 'A'),
  ('hist-fr-318', 'histoire', 'fr', 'hard', 'Quel roi de France a été surnommé Saint Louis et est mort lors d''une croisade ?', 'Philippe II Auguste', 'Louis IX', 'Charles IV', 'Philippe IV le Bel', 'B'),
  ('hist-fr-319', 'histoire', 'fr', 'hard', 'Quel document de 1689 a établi la monarchie constitutionnelle en Angleterre ?', 'La Magna Carta', 'L''Acte d''Union', 'Le Bill of Rights', 'L''Habeas Corpus', 'C'),
  ('hist-fr-320', 'histoire', 'fr', 'hard', 'Quel général carthaginois a mis en déroute les Romains à la bataille de Cannes en 216 av. J.-C. ?', 'Hasdrubal', 'Hamilcar', 'Scipion', 'Hannibal', 'D'),
  ('hist-fr-321', 'histoire', 'fr', 'hard', 'Quel empire a régné sur l''Espagne et une partie de l''Europe pendant près de 800 ans ?', 'L''Empire romain', 'L''Empire byzantin', 'L''Empire ottoman', 'L''Empire maure (califat de Cordoue)', 'D'),
  ('hist-fr-322', 'histoire', 'fr', 'hard', 'Qui était le dernier roi des Français avant la IIe République en 1848 ?', 'Charles X', 'Louis XVIII', 'Louis-Philippe I', 'Napoléon III', 'C'),
  ('hist-en-003', 'histoire', 'en', 'easy', 'Who was the first President of the United States?', 'Abraham Lincoln', 'Thomas Jefferson', 'George Washington', 'Benjamin Franklin', 'C'),
  ('hist-en-008', 'histoire', 'en', 'easy', 'Which treaty ended World War I?', 'Treaty of Paris', 'Treaty of Utrecht', 'Treaty of Versailles', 'Treaty of Westphalia', 'C'),
  ('hist-en-020', 'histoire', 'en', 'easy', 'Which wall fell in 1989?', 'The Great Wall of China', 'The Berlin Wall', 'Hadrian''s Wall', 'The Wall of Constantinople', 'B'),
  ('hist-en-101', 'histoire', 'en', 'easy', 'Which famous monument is found in Egypt?', 'The Colosseum', 'The Pyramids', 'The Parthenon', 'The Eiffel Tower', 'B'),
  ('hist-en-102', 'histoire', 'en', 'easy', 'What is the name of the ancient Egyptian writing system?', 'Runes', 'Cuneiform', 'The alphabet', 'Hieroglyphs', 'D'),
  ('hist-en-103', 'histoire', 'en', 'easy', 'Which people built the Colosseum in Rome?', 'The Greeks', 'The Gauls', 'The Romans', 'The Egyptians', 'C'),
  ('hist-en-104', 'histoire', 'en', 'easy', 'What are Viking ships called?', 'Galleys', 'Caravels', 'Junks', 'Longships', 'D'),
  ('hist-en-105', 'histoire', 'en', 'easy', 'Which king had the Palace of Versailles built?', 'Napoleon', 'Louis XVI', 'Louis XIV', 'Henry IV', 'C'),
  ('hist-en-106', 'histoire', 'en', 'easy', 'In which year did World War I begin?', '1904', '1914', '1924', '1939', 'B'),
  ('hist-en-107', 'histoire', 'en', 'easy', 'Who was the first person to walk on the Moon?', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn', 'Neil Armstrong', 'D'),
  ('hist-en-108', 'histoire', 'en', 'easy', 'Which city was destroyed by the eruption of Mount Vesuvius in 79 AD?', 'Naples', 'Rome', 'Pompeii', 'Carthage', 'C'),
  ('hist-en-109', 'histoire', 'en', 'easy', 'Which animal did Hannibal use to cross the Alps?', 'Horses', 'Camels', 'Elephants', 'Donkeys', 'C'),
  ('hist-en-110', 'histoire', 'en', 'easy', 'Who was the king of the gods in Greek mythology?', 'Poseidon', 'Ares', 'Apollo', 'Zeus', 'D'),
  ('hist-en-111', 'histoire', 'en', 'easy', 'Which explorer completed the first circumnavigation of the Earth?', 'Columbus', 'Vasco da Gama', 'Magellan', 'Cartier', 'C'),
  ('hist-en-112', 'histoire', 'en', 'easy', 'Who was the king of the Franks crowned in the year 800?', 'Clovis', 'Pepin', 'Charlemagne', 'Charles Martel', 'C'),
  ('hist-en-113', 'histoire', 'en', 'easy', 'In which year did World War II end?', '1943', '1944', '1946', '1945', 'D'),
  ('hist-en-114', 'histoire', 'en', 'easy', 'Which country built the Great Wall?', 'Japan', 'Mongolia', 'China', 'India', 'C'),
  ('hist-en-115', 'histoire', 'en', 'easy', 'Who was the Gaul leader who resisted Julius Caesar?', 'Asterix', 'Ambiorix', 'Brennus', 'Vercingetorix', 'D'),
  ('hist-en-116', 'histoire', 'en', 'easy', 'Which French king was nicknamed the Sun King?', 'Louis XIII', 'Henry IV', 'Francis I', 'Louis XIV', 'D'),
  ('hist-en-117', 'histoire', 'en', 'easy', 'Where did the ancient Greeks hold the first Olympic Games?', 'In Athens', 'In Sparta', 'In Olympia', 'In Corinth', 'C'),
  ('hist-en-118', 'histoire', 'en', 'easy', 'Who was the first human to travel to space?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn', 'C'),
  ('hist-en-119', 'histoire', 'en', 'easy', 'Which people lived in Mesopotamia and invented writing?', 'The Egyptians', 'The Persians', 'The Babylonians', 'The Sumerians', 'D'),
  ('hist-en-120', 'histoire', 'en', 'easy', 'Who invented the printing press in Europe in the 15th century?', 'Leonardo da Vinci', 'Gutenberg', 'Copernicus', 'Galileo', 'B'),
  ('hist-en-121', 'histoire', 'en', 'easy', 'Which people invented democracy in Antiquity?', 'The Romans', 'The Persians', 'The Greeks', 'The Egyptians', 'C'),
  ('hist-en-122', 'histoire', 'en', 'easy', 'What was the name of the French warrior who helped liberate Orleans?', 'Marie-Antoinette', 'Joan of Arc', 'Eleanor of Aquitaine', 'Isabella of France', 'B'),
  ('hist-en-002', 'histoire', 'en', 'medium', 'Which pharaoh is associated with the Great Pyramid of Giza?', 'Ramesses II', 'Khufu', 'Akhenaten', 'Tutankhamun', 'B'),
  ('hist-en-004', 'histoire', 'en', 'medium', 'Which empire was ruled by Julius Caesar?', 'The Greek Empire', 'The Roman Empire', 'The Persian Empire', 'The Egyptian Empire', 'B'),
  ('hist-en-018', 'histoire', 'en', 'medium', 'Who was the first emperor of Rome?', 'Julius Caesar', 'Nero', 'Augustus', 'Tiberius', 'C'),
  ('hist-en-037', 'histoire', 'en', 'medium', 'In which year did the French Revolution begin?', '1776', '1783', '1789', '1793', 'C'),
  ('hist-en-201', 'histoire', 'en', 'medium', 'Which civilization built Machu Picchu?', 'The Aztecs', 'The Maya', 'The Incas', 'The Olmecs', 'C'),
  ('hist-en-202', 'histoire', 'en', 'medium', 'In which year did the Ottoman Empire conquer Constantinople?', '1389', '1415', '1453', '1492', 'C'),
  ('hist-en-203', 'histoire', 'en', 'medium', 'Who founded the Mongol Empire in the 13th century?', 'Tamerlane', 'Kublai Khan', 'Attila', 'Genghis Khan', 'D'),
  ('hist-en-204', 'histoire', 'en', 'medium', 'In which country was the Magna Carta signed in 1215?', 'France', 'Italy', 'England', 'Spain', 'C'),
  ('hist-en-205', 'histoire', 'en', 'medium', 'Who was the first leader of the USSR?', 'Trotsky', 'Stalin', 'Khrushchev', 'Lenin', 'D'),
  ('hist-en-206', 'histoire', 'en', 'medium', 'Which conquistador conquered the Aztec Empire?', 'Francisco Pizarro', 'Hernán Cortés', 'Vasco da Gama', 'Amerigo Vespucci', 'B'),
  ('hist-en-207', 'histoire', 'en', 'medium', 'Which ancient civilization invented representative democracy?', 'Rome', 'Athens', 'Carthage', 'Babylon', 'B'),
  ('hist-en-208', 'histoire', 'en', 'medium', 'Which king of England founded the Church of England?', 'Richard I', 'Edward VI', 'Henry VIII', 'James I', 'C'),
  ('hist-en-209', 'histoire', 'en', 'medium', 'Which empire was overthrown by Alexander the Great?', 'The Roman Empire', 'The Babylonian Empire', 'The Egyptian Empire', 'The Persian Empire', 'D'),
  ('hist-en-210', 'histoire', 'en', 'medium', 'In which year did Napoleon become Emperor of France?', '1799', '1801', '1804', '1807', 'C'),
  ('hist-en-211', 'histoire', 'en', 'medium', 'Which military alliance was created by Western nations in 1949?', 'The UN', 'The Warsaw Pact', 'The USSR', 'NATO', 'D'),
  ('hist-en-212', 'histoire', 'en', 'medium', 'Which Portuguese navigator discovered the sea route to India?', 'Bartolomeu Dias', 'Christopher Columbus', 'Vasco da Gama', 'Pedro Álvares Cabral', 'C'),
  ('hist-en-213', 'histoire', 'en', 'medium', 'Which ancient city was the great rival of Rome in the Mediterranean?', 'Athens', 'Alexandria', 'Carthage', 'Corinth', 'C'),
  ('hist-en-214', 'histoire', 'en', 'medium', 'In which year did World War II begin?', '1937', '1938', '1940', '1939', 'D'),
  ('hist-en-215', 'histoire', 'en', 'medium', 'Which event triggered World War I?', 'The invasion of Poland', 'The Russian Revolution', 'The assassination of Archduke Franz Ferdinand', 'The annexation of Alsace', 'C'),
  ('hist-en-216', 'histoire', 'en', 'medium', 'Which pharaoh is known for imposing the worship of a single god in Egypt?', 'Ramesses II', 'Akhenaten', 'Tutankhamun', 'Thutmose', 'B'),
  ('hist-en-217', 'histoire', 'en', 'medium', 'Which revolution overthrew Tsar Nicholas II of Russia?', 'The American Revolution', 'The French Revolution', 'The Russian Revolution', 'The Industrial Revolution', 'C'),
  ('hist-en-218', 'histoire', 'en', 'medium', 'How many years did the Hundred Years'' War between France and England last?', 'About 50 years', 'About 75 years', 'About 100 years', 'About 116 years', 'D'),
  ('hist-en-219', 'histoire', 'en', 'medium', 'Which agreement ended the Napoleonic Wars in 1815?', 'The Treaty of Westphalia', 'The Congress of Vienna', 'The Treaty of Utrecht', 'The Treaty of Versailles', 'B'),
  ('hist-en-220', 'histoire', 'en', 'medium', 'Which conquistador conquered the Inca Empire?', 'Hernán Cortés', 'Vasco da Gama', 'Francisco Pizarro', 'Juan Ponce de León', 'C'),
  ('hist-en-221', 'histoire', 'en', 'medium', 'Which people founded Carthage in North Africa?', 'The Greeks', 'The Phoenicians', 'The Romans', 'The Berbers', 'B'),
  ('hist-en-001', 'histoire', 'en', 'hard', 'Who was the leader of Nazi Germany during World War II?', 'Mussolini', 'Franco', 'Hitler', 'Stalin', 'C'),
  ('hist-en-010', 'histoire', 'en', 'hard', 'Who was the Soviet leader during the Cuban Missile Crisis?', 'Stalin', 'Brezhnev', 'Gorbachev', 'Khrushchev', 'D'),
  ('hist-en-013', 'histoire', 'en', 'hard', 'Who discovered America in 1492?', 'Amerigo Vespucci', 'Vasco da Gama', 'Magellan', 'Christopher Columbus', 'D'),
  ('hist-en-301', 'histoire', 'en', 'hard', 'Who wrote ''The Gallic Wars'', a firsthand account of his military conquests?', 'Cicero', 'Tacitus', 'Virgil', 'Julius Caesar', 'D'),
  ('hist-en-302', 'histoire', 'en', 'hard', 'Which treaty ended the Thirty Years'' War in 1648?', 'Treaty of Utrecht', 'Treaty of Paris', 'Treaty of Westphalia', 'Treaty of Vienna', 'C'),
  ('hist-en-303', 'histoire', 'en', 'hard', 'Which battle in 732 stopped the advance of the Moors into France?', 'Battle of Verdun', 'Battle of Poitiers', 'Battle of Alesia', 'Battle of Marignano', 'B'),
  ('hist-en-304', 'histoire', 'en', 'hard', 'Which Egyptian queen was allied with Julius Caesar and then Mark Antony?', 'Nefertiti', 'Hatshepsut', 'Nefertari', 'Cleopatra', 'D'),
  ('hist-en-305', 'histoire', 'en', 'hard', 'Which Greek philosopher was the tutor of Alexander the Great?', 'Plato', 'Socrates', 'Aristotle', 'Pythagoras', 'C'),
  ('hist-en-306', 'histoire', 'en', 'hard', 'In which year was Louis XVI guillotined during the French Revolution?', '1791', '1792', '1793', '1795', 'C'),
  ('hist-en-307', 'histoire', 'en', 'hard', 'What is the name of the battle where Napoleon was definitively defeated in 1815?', 'Austerlitz', 'Borodino', 'Waterloo', 'Leipzig', 'C'),
  ('hist-en-308', 'histoire', 'en', 'hard', 'Which Roman emperor adopted Christianity as the official religion of the Empire?', 'Augustus', 'Tiberius', 'Diocletian', 'Constantine', 'D'),
  ('hist-en-309', 'histoire', 'en', 'hard', 'Which African empire was known for its wealth and its king Mansa Musa in the 14th century?', 'Empire of Ghana', 'Mali Empire', 'Songhai Empire', 'Kingdom of Zimbabwe', 'B'),
  ('hist-en-310', 'histoire', 'en', 'hard', 'In which year is the fall of the Western Roman Empire dated?', '370 AD', '410 AD', '476 AD', '527 AD', 'C'),
  ('hist-en-311', 'histoire', 'en', 'hard', 'Which Viking leader founded the Duchy of Normandy in the 10th century?', 'Ragnar Lothbrok', 'Erik the Red', 'Leif Erikson', 'Rollo', 'D'),
  ('hist-en-312', 'histoire', 'en', 'hard', 'Which empire was founded by Cyrus the Great in the 6th century BC?', 'Babylonian Empire', 'Median Empire', 'Persian Empire', 'Assyrian Empire', 'C'),
  ('hist-en-313', 'histoire', 'en', 'hard', 'Which American plan helped rebuild Europe after World War II?', 'The Dawes Plan', 'The Schuman Plan', 'The New Deal', 'The Marshall Plan', 'D'),
  ('hist-en-314', 'histoire', 'en', 'hard', 'Who wrote ''The Art of War'', an ancient Chinese military treatise?', 'Confucius', 'Lao Tzu', 'Sun Tzu', 'Mao Zedong', 'C'),
  ('hist-en-315', 'histoire', 'en', 'hard', 'Which country launched the first artificial satellite, Sputnik, in 1957?', 'United States', 'France', 'Germany', 'USSR', 'D'),
  ('hist-en-316', 'histoire', 'en', 'hard', 'Which pharaoh is often associated with the Exodus of the Hebrews according to the Bible?', 'Amenhotep III', 'Akhenaten', 'Ramesses II', 'Thutmose III', 'C'),
  ('hist-en-317', 'histoire', 'en', 'hard', 'Which war pitted Athens against Sparta from 431 to 404 BC?', 'The Peloponnesian War', 'The Persian Wars', 'The Trojan War', 'The Corinthian War', 'A'),
  ('hist-en-318', 'histoire', 'en', 'hard', 'Which French king was nicknamed Saint Louis and died during a Crusade?', 'Philip II Augustus', 'Louis IX', 'Charles IV', 'Philip IV the Fair', 'B'),
  ('hist-en-319', 'histoire', 'en', 'hard', 'Which English document of 1689 established constitutional monarchy?', 'The Magna Carta', 'The Act of Union', 'The Bill of Rights', 'The Habeas Corpus', 'C'),
  ('hist-en-320', 'histoire', 'en', 'hard', 'Which Carthaginian general defeated the Romans at the Battle of Cannae in 216 BC?', 'Hasdrubal', 'Hamilcar', 'Scipio', 'Hannibal', 'D'),
  ('hist-en-321', 'histoire', 'en', 'hard', 'Which empire ruled Spain and part of Europe for nearly 800 years?', 'The Roman Empire', 'The Byzantine Empire', 'The Ottoman Empire', 'The Moorish Empire (Caliphate of Cordoba)', 'D'),
  ('hist-en-322', 'histoire', 'en', 'hard', 'Who was the last King of the French before the Second Republic in 1848?', 'Charles X', 'Louis XVIII', 'Louis-Philippe I', 'Napoleon III', 'C'),
  ('hero-fr-easy-001', 'heroes', 'fr', 'easy', 'Qui garde un château souvent ?', 'Chevalier', 'Paysan', 'Boulanger', 'Peintre', 'A'),
  ('hero-fr-easy-002', 'heroes', 'fr', 'easy', 'Qui navigue sur un bateau large ?', 'Pirate', 'Bibliothécaire', 'Docteur', 'Jardinier', 'A'),
  ('hero-fr-easy-003', 'heroes', 'fr', 'easy', 'Quel animal crache du feu dans les histoires ?', 'Dragon', 'Chien', 'Cheval', 'Mouton', 'A'),
  ('hero-fr-easy-004', 'heroes', 'fr', 'easy', 'Qui lance des sorts en général ?', 'Sorcier', 'Forgeron', 'Fermier', 'Marin', 'A'),
  ('hero-fr-easy-005', 'heroes', 'fr', 'easy', 'Qui porte une épée brillante ?', 'Chevalier', 'Poète', 'Cuisinier', 'Tailleur', 'A'),
  ('hero-fr-easy-006', 'heroes', 'fr', 'easy', 'Qui cherche un trésor sur une île ?', 'Pirate', 'Médecin', 'Facteur', 'Gentilhomme', 'A'),
  ('hero-fr-easy-007', 'heroes', 'fr', 'easy', 'Quel objet protège la tête du chevalier ?', 'Bouclier', 'Casque', 'Bottes', 'Gants', 'B'),
  ('hero-fr-easy-008', 'heroes', 'fr', 'easy', 'Qui aide les gens avec des pouvoirs ?', 'Super-héros', 'Coiffeur', 'Vendeur', 'Mineur', 'A'),
  ('hero-fr-easy-009', 'heroes', 'fr', 'easy', 'Qui navigue avec une carte au trésor ?', 'Boulangère', 'Pirate', 'Professeur', 'Gardien', 'B'),
  ('hero-fr-easy-010', 'heroes', 'fr', 'easy', 'Quel héros porte une cape souvent ?', 'Magicien', 'Livreur', 'Charpentier', 'Banquier', 'A'),
  ('hero-fr-easy-011', 'heroes', 'fr', 'easy', 'Qui protège la ville la nuit ?', 'Gardien', 'Chevalier', 'Pirate', 'Sage', 'B'),
  ('hero-fr-easy-012', 'heroes', 'fr', 'easy', 'Qui grimpe les voiles du navire ?', 'Marin', 'Forgeron', 'Peintre', 'Tisserand', 'A'),
  ('hero-fr-easy-013', 'heroes', 'fr', 'easy', 'Qui bat les monstres dans les contes ?', 'Héros', 'Biscuit', 'Chaise', 'Rivière', 'A'),
  ('hero-fr-easy-014', 'heroes', 'fr', 'easy', 'Quel instrument un barde joue-t-il ?', 'Luth', 'Serpe', 'Marteau', 'Clé', 'A'),
  ('hero-fr-easy-015', 'heroes', 'fr', 'easy', 'Qui suit une carte et une boussole ?', 'Aventurier', 'Couturier', 'Jardinier', 'Livreur', 'A'),
  ('hero-fr-easy-016', 'heroes', 'fr', 'easy', 'Quel animal protège parfois un trésor ?', 'Dragon', 'Lapin', 'Chèvre', 'Oiseau', 'A'),
  ('hero-fr-easy-017', 'heroes', 'fr', 'easy', 'Qui suit des indices pour un trésor ?', 'Détective', 'Pirate', 'Boulanger', 'Réparateur', 'B'),
  ('hero-fr-easy-018', 'heroes', 'fr', 'easy', 'Quel objet protège du feu magique ?', 'Cape anti-feu', 'Tasse', 'Table', 'Chaise', 'A'),
  ('hero-fr-easy-019', 'heroes', 'fr', 'easy', 'Qui sait lire d''anciennes cartes ?', 'Cartographe', 'Boulanger', 'Chanteur', 'Boucher', 'A'),
  ('hero-fr-easy-020', 'heroes', 'fr', 'easy', 'Qui part à la quête d''une île perdue ?', 'Aventurier', 'Coiffeur', 'Écrivain', 'Mécanicien', 'A'),
  ('hero-fr-easy-021', 'heroes', 'fr', 'easy', 'Quel héros protège les faibles ?', 'Chevalier', 'Voleur', 'Contrebandier', 'Marchand', 'A'),
  ('hero-fr-easy-022', 'heroes', 'fr', 'easy', 'Quel objet aide à parler aux animaux ?', 'Amulette', 'Balai', 'Chaise', 'Livre de recettes', 'A'),
  ('hero-fr-easy-023', 'heroes', 'fr', 'easy', 'Qui défie les vagues pour explorer ?', 'Marin', 'Charpentier', 'Couturier', 'Menuisier', 'A'),
  ('hero-fr-easy-024', 'heroes', 'fr', 'easy', 'Quel héros porte souvent une épée ?', 'Chevalier', 'Poète', 'Apiculteur', 'Jongleur', 'A'),
  ('hero-fr-easy-025', 'heroes', 'fr', 'easy', 'Qui défend la cité contre des monstres ?', 'Gardien', 'Cuisinier', 'Tisserand', 'Pêcheur', 'A'),
  ('hero-fr-medium-001', 'heroes', 'fr', 'medium', 'Quel est le code d''honneur d''un chevalier ?', 'Voler', 'Courage et loyauté', 'Ignorer les autres', 'Mentir', 'B'),
  ('hero-fr-medium-002', 'heroes', 'fr', 'medium', 'Que cherchent souvent les pirates en mer ?', 'Trésors enfouis', 'Jardins', 'Écoles', 'Bibliothèques', 'A'),
  ('hero-fr-medium-003', 'heroes', 'fr', 'medium', 'Quel outil un cartographe utilise-t-il ?', 'Boussole', 'Fourche', 'Microphone', 'Telescope', 'A'),
  ('hero-fr-medium-004', 'heroes', 'fr', 'medium', 'Quel héros protège le royaume la nuit ?', 'Bouffon', 'Chevalier', 'Forgeron', 'Marchand', 'B'),
  ('hero-fr-medium-005', 'heroes', 'fr', 'medium', 'Quelle créature garde souvent un trésor ?', 'Dragon', 'Mouton', 'Singe', 'Chèvre', 'A'),
  ('hero-fr-medium-006', 'heroes', 'fr', 'medium', 'Quel pouvoir protège contre la magie noire ?', 'Amulette de protection', 'Bouteille d''eau', 'Clé', 'Tasse', 'A'),
  ('hero-fr-medium-007', 'heroes', 'fr', 'medium', 'Que fait un éclaireur dans une quête ?', 'Explorer avant le groupe', 'Prendre le trésor', 'Cuisiner pour tous', 'Dormir', 'A'),
  ('hero-fr-medium-008', 'heroes', 'fr', 'medium', 'Quel rôle tient un barde parmi les aventuriers ?', 'Chanteur et conteur', 'Forgeron', 'Charpentier', 'Guerrier uniquement', 'A'),
  ('hero-fr-medium-009', 'heroes', 'fr', 'medium', 'Quelle arme un pirate préfère-t-il souvent ?', 'Sabre', 'Épée de cérémonie', 'Arc', 'Fourchette', 'A'),
  ('hero-fr-medium-010', 'heroes', 'fr', 'medium', 'Quel danger évite un navigateur avec une carte ?', 'Rochers cachés', 'Tempêtes seulement', 'Sables', 'Plantes', 'A'),
  ('hero-fr-medium-011', 'heroes', 'fr', 'medium', 'Quel test sert à reconnaître une épée forgée ?', 'Son poids', 'Qualité de l''acier', 'Couleur du four', 'Taille de la garde', 'B'),
  ('hero-fr-medium-012', 'heroes', 'fr', 'medium', 'Comment un magicien concentre-t-il son pouvoir ?', 'Par la méditation', 'En courant', 'En criant', 'En dormant', 'A'),
  ('hero-fr-medium-013', 'heroes', 'fr', 'medium', 'Quel paysage attire souvent les aventuriers ?', 'Forêt mystérieuse', 'Autoroute', 'Usine', 'Parking', 'A'),
  ('hero-fr-medium-014', 'heroes', 'fr', 'medium', 'Quel objet révèle une carte secrète ?', 'Lanterne magique', 'Chaise', 'Planche', 'Bouteille', 'A'),
  ('hero-fr-medium-015', 'heroes', 'fr', 'medium', 'Que protège un bouclier enchanté ?', 'Seuls vêtements', 'Attaques et sorts', 'La faim', 'Le sommeil', 'B'),
  ('hero-fr-medium-016', 'heroes', 'fr', 'medium', 'Quel allié un chevalier cherche-t-il ?', 'Compagnon loyal', 'Rival jaloux', 'Vendeur', 'Lézard', 'A'),
  ('hero-fr-medium-017', 'heroes', 'fr', 'medium', 'Comment appelle-t-on une carte ancienne secrète ?', 'Manuel', 'Carte au trésor', 'Journal intime', 'Reçu', 'B'),
  ('hero-fr-medium-018', 'heroes', 'fr', 'medium', 'Quel obstacle un navire redoute-t-il ?', 'Récifs', 'Terre ferme', 'Bancs de sable seulement', 'Vagues calmes', 'A'),
  ('hero-fr-medium-019', 'heroes', 'fr', 'medium', 'Quel sort soigne généralement les blessures ?', 'Sort de guérison', 'Sort de peur', 'Sort d''invisibilité', 'Sort de rouille', 'A'),
  ('hero-fr-medium-020', 'heroes', 'fr', 'medium', 'Quel métier a le savoir des cartes et routes ?', 'Cartographe', 'Couturier', 'Fabricant de meubles', 'Boucher', 'A'),
  ('hero-fr-medium-021', 'heroes', 'fr', 'medium', 'Quel défi un chevalier doit souvent relever ?', 'Un duel pour l''honneur', 'Un cours de cuisine', 'Une vente aux enchères', 'Un match de foot', 'A'),
  ('hero-fr-medium-022', 'heroes', 'fr', 'medium', 'Quelle qualité est essentielle pour un aventurier ?', 'Curiosité', 'Paresse', 'Indifférence', 'Méfiance totale', 'A'),
  ('hero-fr-medium-023', 'heroes', 'fr', 'medium', 'Quelle créature mythique a la tête d''un homme et corps de lion ?', 'Sphinx', 'Licorne', 'Griffon', 'Hydre', 'A'),
  ('hero-fr-medium-024', 'heroes', 'fr', 'medium', 'Quel artefact éclaire les grottes sombres ?', 'Lanterne enchantée', 'Tasse magique', 'Robe brillante', 'Bûche', 'A'),
  ('hero-fr-medium-025', 'heroes', 'fr', 'medium', 'Quel animal sert souvent de monture légendaire ?', 'Cheval', 'Poulet', 'Souris', 'Tortue', 'A'),
  ('hero-fr-hard-001', 'heroes', 'fr', 'hard', 'Quelle tactique use un chevalier pour briser une armure ?', 'Coup direct au heaume', 'Trancher un drap', 'Chuchoter', 'Lancer des fleurs', 'A'),
  ('hero-fr-hard-002', 'heroes', 'fr', 'hard', 'Quelle était une vraie menace pour les navires anciens ?', 'Scurvy (manque de vitamine C)', 'Téléphone déchargé', 'Feux de signalisation', 'Pneus usés', 'A'),
  ('hero-fr-hard-003', 'heroes', 'fr', 'hard', 'Quelle propriété rend une lame de bonne qualité ?', 'Dureté et flexibilité', 'Couleur', 'Taille du manche uniquement', 'Poids excessif', 'A'),
  ('hero-fr-hard-004', 'heroes', 'fr', 'hard', 'Quel principe guide une expédition réussie ?', 'Planification et cartes fiables', 'Ignorer la météo', 'Partir sans provisions', 'Chercher des disputes', 'A'),
  ('hero-fr-hard-005', 'heroes', 'fr', 'hard', 'Quelle stratégie défensive pour un château ?', 'Murs élevés et fossés', 'Portes ouvertes', 'Aucun guet', 'Toit en verre', 'A'),
  ('hero-fr-hard-006', 'heroes', 'fr', 'hard', 'Quel savoir aide à déchiffrer une ancienne tablette ?', 'Connaissance des symboles', 'Conduite automobile', 'Cuisine', 'Natation', 'A'),
  ('hero-fr-hard-007', 'heroes', 'fr', 'hard', 'Quel élément protège contre la rouille d''une armure ?', 'Graissage régulier', 'Exposition à l''eau', 'Ignorance', 'Rouler sur l''armure', 'A'),
  ('hero-fr-hard-008', 'heroes', 'fr', 'hard', 'Quelle route maritime évitait les pirates ?', 'Zones surveillées et convois', 'Eaux isolées', 'Côtes inconnues', 'Ports éloignés', 'A'),
  ('hero-fr-hard-009', 'heroes', 'fr', 'hard', 'Quel test vérifie si une potion est toxique ?', 'Analyse et dilution contrôlée', 'Goûter sans protection', 'Lancer au feu', 'Mettre au soleil', 'A'),
  ('hero-fr-hard-010', 'heroes', 'fr', 'hard', 'Quelle tactique pour traverser une forêt hostile ?', 'Suivre sentiers et repères', 'Se séparer sans plan', 'Ignorer provisions', 'Courir sans regarder', 'A'),
  ('hero-fr-hard-011', 'heroes', 'fr', 'hard', 'Quel principe gouverne une quête réussie ?', 'But clair et coopération', 'Égoïsme', 'Quitter tôt', 'Désorganisation', 'A'),
  ('hero-fr-hard-012', 'heroes', 'fr', 'hard', 'Quelle compétence aide à négocier avec un seigneur ?', 'Diplomatie', 'Cri', 'Course', 'Dormir', 'A'),
  ('hero-fr-hard-013', 'heroes', 'fr', 'hard', 'Quel signe montre une carte codée ?', 'Symboles répétitifs', 'Taches de café', 'Marge propre', 'Papier neuf', 'A'),
  ('hero-fr-hard-014', 'heroes', 'fr', 'hard', 'Quelle tactique repousse un dragon dans les contes ?', 'Feu plus fort', 'Bouclier réfléchissant la chaleur', 'Chanter fort', 'Offrir une chaise', 'B'),
  ('hero-fr-hard-015', 'heroes', 'fr', 'hard', 'Quelle préparation est essentielle avant une traversée longue ?', 'Provisions, eau et cartes', 'Rien', 'Juste des habits', 'Se laisser guider par hasard', 'A'),
  ('hero-fr-hard-016', 'heroes', 'fr', 'hard', 'Quel enseignement un forgeron transmet-il au chevalier ?', 'Entretien de l''arme', 'Cuisine', 'Peinture', 'Musique', 'A'),
  ('hero-fr-hard-017', 'heroes', 'fr', 'hard', 'Quelle ressource protège une cité en siège ?', 'Eau et vivres stockés', 'Tapisseries', 'Bougies seulement', 'Fleurs', 'A'),
  ('hero-fr-hard-018', 'heroes', 'fr', 'hard', 'Quelle connaissance aide à traverser un marais ?', 'Connaître les voies sûres', 'Courir vite', 'Siffler', 'Allumer un feu', 'A'),
  ('hero-fr-hard-019', 'heroes', 'fr', 'hard', 'Quel art aide à persuader un roi ?', 'Oratoire', 'Jonglage', 'Saut', 'Couture', 'A'),
  ('hero-fr-hard-020', 'heroes', 'fr', 'hard', 'Quel avantage offre une armée bien organisée ?', 'Coordination et stratégie', 'Chaos', 'Chaos contrôlé', 'Plus de chants', 'A'),
  ('hero-fr-hard-021', 'heroes', 'fr', 'hard', 'Quel savoir protège contre les illusions magiques ?', 'Rituels de dissipation', 'Ignorer tout', 'Fermer les yeux', 'Manger une pomme', 'A'),
  ('hero-fr-hard-022', 'heroes', 'fr', 'hard', 'Quelle ressource un explorateur doit-il cartographier ?', 'Sources d''eau', 'Couleurs des drapeaux', 'Textes poétiques', 'Vêtements', 'A'),
  ('hero-fr-hard-023', 'heroes', 'fr', 'hard', 'Quelle compétence militaire est essentielle pour un chef ?', 'Stratégie et tactique', 'Coudre des bannières', 'Raconter des blagues', 'Faire des comptes', 'A'),
  ('hero-fr-hard-024', 'heroes', 'fr', 'hard', 'Quelle tactique détourne l''attention d''un ennemi ?', 'Feinte', 'Sommeil', 'Répéter des ordres', 'Méditation', 'A'),
  ('hero-fr-hard-025', 'heroes', 'fr', 'hard', 'Quel principe gouverne un code héroïque durable ?', 'Honneur, courage et respect', 'Ruse seule', 'Peur uniquement', 'Silence total', 'A'),
  ('hero-en-easy-001', 'heroes', 'en', 'easy', 'Who protects a castle in stories?', 'Knight', 'Farmer', 'Baker', 'Painter', 'A'),
  ('hero-en-easy-002', 'heroes', 'en', 'easy', 'Who sails a pirate ship?', 'Pirate', 'Doctor', 'Tailor', 'Gardener', 'A'),
  ('hero-en-easy-003', 'heroes', 'en', 'easy', 'Which creature breathes fire in tales?', 'Dragon', 'Sheep', 'Horse', 'Cat', 'A'),
  ('hero-en-easy-004', 'heroes', 'en', 'easy', 'Who casts spells in many stories?', 'Wizard', 'Carpenter', 'Baker', 'Tailor', 'A'),
  ('hero-en-easy-005', 'heroes', 'en', 'easy', 'Who wears shining armor?', 'Knight', 'Poet', 'Cook', 'Farmer', 'A'),
  ('hero-en-easy-006', 'heroes', 'en', 'easy', 'Who looks for treasure on islands?', 'Pirate', 'Teacher', 'Driver', 'Painter', 'A'),
  ('hero-en-easy-007', 'heroes', 'en', 'easy', 'What protects a knight''s head?', 'Helmet', 'Boot', 'Glove', 'Shoe', 'A'),
  ('hero-en-easy-008', 'heroes', 'en', 'easy', 'Who has superpowers and helps others?', 'Superhero', 'Baker', 'Driver', 'Farmer', 'A'),
  ('hero-en-easy-009', 'heroes', 'en', 'easy', 'Who follows a treasure map?', 'Pirate', 'Chef', 'Tailor', 'Teacher', 'A'),
  ('hero-en-easy-010', 'heroes', 'en', 'easy', 'Who often wears a magic cape?', 'Mage', 'Carpenter', 'Butcher', 'Driver', 'A'),
  ('hero-en-easy-011', 'heroes', 'en', 'easy', 'Who guards the city at night?', 'Guardian', 'Chef', 'Farmer', 'Artist', 'A'),
  ('hero-en-easy-012', 'heroes', 'en', 'easy', 'Who climbs a ship''s mast?', 'Sailor', 'Baker', 'Carpenter', 'Blacksmith', 'A'),
  ('hero-en-easy-013', 'heroes', 'en', 'easy', 'Who defeats monsters in tales?', 'Hero', 'Chair', 'Cloud', 'Spoon', 'A'),
  ('hero-en-easy-014', 'heroes', 'en', 'easy', 'Which instrument does a bard play?', 'Lute', 'Hammer', 'Sewing needle', 'Shovel', 'A'),
  ('hero-en-easy-015', 'heroes', 'en', 'easy', 'Who uses compass and maps on quests?', 'Adventurer', 'Baker', 'Tailor', 'Driver', 'A'),
  ('hero-en-easy-016', 'heroes', 'en', 'easy', 'Which animal often guards treasure?', 'Dragon', 'Cow', 'Dog', 'Cat', 'A'),
  ('hero-en-easy-017', 'heroes', 'en', 'easy', 'Who deciphers clues to find treasure?', 'Detective', 'Baker', 'Cleaner', 'Driver', 'A'),
  ('hero-en-easy-018', 'heroes', 'en', 'easy', 'Which object helps talk to animals?', 'Amulet', 'Fork', 'Book', 'Plate', 'A'),
  ('hero-en-easy-019', 'heroes', 'en', 'easy', 'Who explores distant islands?', 'Explorer', 'Baker', 'Artist', 'Tailor', 'A'),
  ('hero-en-easy-020', 'heroes', 'en', 'easy', 'Which hero often carries a sword?', 'Knight', 'Teacher', 'Doctor', 'Pilot', 'A'),
  ('hero-en-easy-021', 'heroes', 'en', 'easy', 'Who defends the weak in tales?', 'Knight', 'Thief', 'Merchant', 'Baker', 'A'),
  ('hero-en-easy-022', 'heroes', 'en', 'easy', 'What item lets you understand animals?', 'Magic amulet', 'Sword', 'Shield', 'Helmet', 'A'),
  ('hero-en-easy-023', 'heroes', 'en', 'easy', 'Who braves rough seas to explore?', 'Sailor', 'Baker', 'Blacksmith', 'Tailor', 'A'),
  ('hero-en-easy-024', 'heroes', 'en', 'easy', 'Which hero wears a shining shield?', 'Knight', 'Farmer', 'Priest', 'Actor', 'A'),
  ('hero-en-easy-025', 'heroes', 'en', 'easy', 'Who defends a town from monsters?', 'Guardian', 'Chef', 'Tailor', 'Fisher', 'A'),
  ('hero-en-medium-001', 'heroes', 'en', 'medium', 'What does a knight''s code stress?', 'Courage and honor', 'Hiding', 'Stealing', 'Laziness', 'A'),
  ('hero-en-medium-002', 'heroes', 'en', 'medium', 'What do pirates often seek at sea?', 'Treasure', 'Schools', 'Markets', 'Hospitals', 'A'),
  ('hero-en-medium-003', 'heroes', 'en', 'medium', 'Which tool helps mapmakers most?', 'Compass', 'Spoon', 'Broom', 'Knife', 'A'),
  ('hero-en-medium-004', 'heroes', 'en', 'medium', 'Who defends the realm at night?', 'Knight', 'Merchant', 'Farmer', 'Baker', 'A'),
  ('hero-en-medium-005', 'heroes', 'en', 'medium', 'What guards a hoard in legend?', 'Dragon', 'Goat', 'Sheep', 'Rabbit', 'A'),
  ('hero-en-medium-006', 'heroes', 'en', 'medium', 'What protects against dark magic?', 'Protective charm', 'Empty box', 'Broken sword', 'Paper', 'A'),
  ('hero-en-medium-007', 'heroes', 'en', 'medium', 'What role scouts play in quests?', 'Spot danger first', 'Cook food only', 'Sleep a lot', 'Sew clothes', 'A'),
  ('hero-en-medium-008', 'heroes', 'en', 'medium', 'What does a bard bring to a group?', 'Songs and stories', 'Iron alone', 'Heavy armor', 'Food only', 'A'),
  ('hero-en-medium-009', 'heroes', 'en', 'medium', 'Which weapon does a pirate favor?', 'Cutlass', 'Spoon', 'Feather', 'Hammer', 'A'),
  ('hero-en-medium-010', 'heroes', 'en', 'medium', 'What hazard does a map help avoid?', 'Hidden rocks', 'Boring roads', 'Bright sunlight', 'Friendly birds', 'A'),
  ('hero-en-medium-011', 'heroes', 'en', 'medium', 'How judge a blade''s quality?', 'Steel and balance', 'Color only', 'Length only', 'Handle decoration', 'A'),
  ('hero-en-medium-012', 'heroes', 'en', 'medium', 'How does a mage focus power?', 'Meditation', 'Shouting', 'Running', 'Laughing', 'A'),
  ('hero-en-medium-013', 'heroes', 'en', 'medium', 'Which terrain lures many adventurers?', 'Mysterious forest', 'Factory floor', 'Shopping mall', 'Parking lot', 'A'),
  ('hero-en-medium-014', 'heroes', 'en', 'medium', 'Which object can reveal hidden maps?', 'Magic lantern', 'Stone', 'Rope', 'Sack', 'A'),
  ('hero-en-medium-015', 'heroes', 'en', 'medium', 'What does an enchanted shield block?', 'Attacks and spells', 'Hunger', 'Smell', 'Time', 'A'),
  ('hero-en-medium-016', 'heroes', 'en', 'medium', 'What ally does a knight prefer?', 'Loyal companion', 'Loud rival', 'Greedy merchant', 'Silent tree', 'A'),
  ('hero-en-medium-017', 'heroes', 'en', 'medium', 'What name fits an old secret map?', 'Treasure map', 'Menu', 'Receipt', 'Novel', 'A'),
  ('hero-en-medium-018', 'heroes', 'en', 'medium', 'What danger does a ship dread most?', 'Reefs', 'Seagulls', 'Smooth sails', 'Calm weather', 'A'),
  ('hero-en-medium-019', 'heroes', 'en', 'medium', 'Which spell helps heal wounds?', 'Healing spell', 'Fear spell', 'Invisibility', 'Rust spell', 'A'),
  ('hero-en-medium-020', 'heroes', 'en', 'medium', 'Who studies maps and roads?', 'Cartographer', 'Baker', 'Cook', 'Singer', 'A'),
  ('hero-en-medium-021', 'heroes', 'en', 'medium', 'What challenge might a knight face?', 'Duel of honor', 'Baking contest', 'Dance-off', 'Sewing class', 'A'),
  ('hero-en-medium-022', 'heroes', 'en', 'medium', 'Which trait aids an adventurer most?', 'Curiosity', 'Laziness', 'Greed', 'Fear', 'A'),
  ('hero-en-medium-023', 'heroes', 'en', 'medium', 'Which mythical creature has a human head and lion body?', 'Sphinx', 'Unicorn', 'Griffin', 'Hydra', 'A'),
  ('hero-en-medium-024', 'heroes', 'en', 'medium', 'What lights dark caves for explorers?', 'Magic lantern', 'Feather', 'Stone', 'Empty bottle', 'A'),
  ('hero-en-medium-025', 'heroes', 'en', 'medium', 'Which legendary mount aids travel?', 'Horse', 'Mouse', 'Chicken', 'Turtle', 'A'),
  ('hero-en-hard-001', 'heroes', 'en', 'hard', 'What tactic breaks heavy plate armor?', 'Blunt strikes', 'Tickling', 'Singing', 'Waving flags', 'A'),
  ('hero-en-hard-002', 'heroes', 'en', 'hard', 'What disease threatened old sailors on long voyages?', 'Scurvy', 'Cold feet', 'Sore throat', 'Sunburn only', 'A'),
  ('hero-en-hard-003', 'heroes', 'en', 'hard', 'Which quality defines an excellent sword?', 'Balance and tempered steel', 'Bright color', 'Long tassel', 'Heavy rust', 'A'),
  ('hero-en-hard-004', 'heroes', 'en', 'hard', 'What ensures success for a long expedition?', 'Good planning and crew', 'Leaving at random', 'No supplies', 'Ignoring maps', 'A'),
  ('hero-en-hard-005', 'heroes', 'en', 'hard', 'Which defense helps a besieged castle most?', 'Moat and tall walls', 'Open gates', 'No guards', 'Thin walls', 'A'),
  ('hero-en-hard-006', 'heroes', 'en', 'hard', 'What knowledge helps read ancient tablets?', 'Symbol interpretation', 'Cooking recipes', 'Horse riding only', 'Sewing patterns', 'A'),
  ('hero-en-hard-007', 'heroes', 'en', 'hard', 'How prevent armor from rusting?', 'Oil and maintenance', 'Leave in rain', 'Bury it', 'Paint with flour', 'A'),
  ('hero-en-hard-008', 'heroes', 'en', 'hard', 'Which sea route reduced pirate attacks?', 'Convoyed and patrolled lanes', 'Unknown waters', 'Shallow bays', 'Hidden coves', 'A'),
  ('hero-en-hard-009', 'heroes', 'en', 'hard', 'How test whether a potion is harmful?', 'Analyze and dilute carefully', 'Drink immediately', 'Throw it away', 'Smell loudly', 'A'),
  ('hero-en-hard-010', 'heroes', 'en', 'hard', 'What tactic helps cross hostile forests safely?', 'Follow trails and markers', 'Split group randomly', 'Run blindly', 'Sing loudly', 'A'),
  ('hero-en-hard-011', 'heroes', 'en', 'hard', 'What principle guides a successful quest?', 'Clear goal and teamwork', 'Selfishness', 'Hiding always', 'Avoid planning', 'A'),
  ('hero-en-hard-012', 'heroes', 'en', 'hard', 'Which skill helps persuade a lord?', 'Diplomacy', 'Running fast', 'Whistling', 'Carving wood', 'A'),
  ('hero-en-hard-013', 'heroes', 'en', 'hard', 'Which sign indicates a coded map?', 'Repeated symbols', 'Tidy margins', 'Bright colors', 'Blank spots', 'A'),
  ('hero-en-hard-014', 'heroes', 'en', 'hard', 'Which tactic can repel a dragon''s flames?', 'Reflective shield', 'Throwing stones', 'Yelling', 'Running circles', 'A'),
  ('hero-en-hard-015', 'heroes', 'en', 'hard', 'What must travelers pack for a long voyage?', 'Food, water and maps', 'Only clothes', 'Just a hat', 'No supplies', 'A'),
  ('hero-en-hard-016', 'heroes', 'en', 'hard', 'What does a blacksmith teach a knight?', 'Weapon care', 'Dancing steps', 'Cooking soups', 'Singing', 'A'),
  ('hero-en-hard-017', 'heroes', 'en', 'hard', 'Which resource saves a city in siege?', 'Stored water and food', 'Decorations', 'Empty halls', 'Songs', 'A'),
  ('hero-en-hard-018', 'heroes', 'en', 'hard', 'What helps cross a dangerous swamp?', 'Know safe paths', 'Walk anywhere', 'Run quickly', 'Sing loudly', 'A'),
  ('hero-en-hard-019', 'heroes', 'en', 'hard', 'Which art convinces kings and rulers?', 'Oratory', 'Juggling', 'Whistling', 'Sleeping well', 'A'),
  ('hero-en-hard-020', 'heroes', 'en', 'hard', 'What benefit does an organized army bring?', 'Strategy and coordination', 'Chaos', 'Confusion', 'Noise only', 'A'),
  ('hero-en-hard-021', 'heroes', 'en', 'hard', 'How counter magical illusions effectively?', 'Dispel rituals', 'Ignore them', 'Sleep', 'Sneeze', 'A'),
  ('hero-en-hard-022', 'heroes', 'en', 'hard', 'What should explorers map first?', 'Water sources', 'Flowers', 'Bird songs', 'Clouds', 'A'),
  ('hero-en-hard-023', 'heroes', 'en', 'hard', 'Which military skill matters for leaders?', 'Tactics and strategy', 'Painting', 'Baking', 'Sleeping', 'A'),
  ('hero-en-hard-024', 'heroes', 'en', 'hard', 'What is a common battlefield deception?', 'Feint', 'Singing loudly', 'Standing still', 'Showing maps', 'A'),
  ('hero-en-hard-025', 'heroes', 'en', 'hard', 'Which values form a lasting hero code?', 'Honor, courage, respect', 'Trickery alone', 'Fear only', 'Silence', 'A')
ON CONFLICT (id) DO UPDATE SET
  category = EXCLUDED.category,
  locale = EXCLUDED.locale,
  difficulty = EXCLUDED.difficulty,
  question = EXCLUDED.question,
  option_a = EXCLUDED.option_a,
  option_b = EXCLUDED.option_b,
  option_c = EXCLUDED.option_c,
  option_d = EXCLUDED.option_d,
  answer = EXCLUDED.answer;

-- Total : 450 questions
