"""Ajoute 101 questions FR heroes (1 easy + 100 hard) pour atteindre 600."""
import json, random
from pathlib import Path

NEW_QUESTIONS = [
  # easy (1)
  {"id":"heroes-fr-easy-200","category":"heros","subcategory":None,"locale":"fr","difficulty":"easy","question":"Quel est le nom du petit garçon qui apprend la magie dans la série Harry Potter ?","options":{"A":"Harry Potter","B":"Ron Weasley","C":"Neville Londubat","D":"Drago Malefoy"},"answer":"A"},
  # hard (100)
  {"id":"heroes-fr-hard-101","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie grecque, quel héros a tué le Minotaure en s'aidant d'un fil ?","options":{"A":"Persée","B":"Thésée","C":"Ulysse","D":"Achille"},"answer":"B"},
  {"id":"heroes-fr-hard-102","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel auteur français a créé le personnage d'Arsène Lupin ?","options":{"A":"Jules Verne","B":"Alexandre Dumas","C":"Maurice Leblanc","D":"Victor Hugo"},"answer":"C"},
  {"id":"heroes-fr-hard-103","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans l'épopée de Gilgamesh, quelle quête mène le héros après la mort de son ami Enkidu ?","options":{"A":"La vengeance contre les dieux","B":"L'immortalité","C":"La reconstruction d'Uruk","D":"La capture du taureau céleste"},"answer":"B"},
  {"id":"heroes-fr-hard-104","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros nordique est fils d'Odin et possède un marteau appelé Mjöllnir ?","options":{"A":"Loki","B":"Freyr","C":"Thor","D":"Tyr"},"answer":"C"},
  {"id":"heroes-fr-hard-105","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la légende arthurienne, quel chevalier est le père de Galaad et est considéré comme le meilleur guerrier ?","options":{"A":"Gauvain","B":"Perceval","C":"Bohort","D":"Lancelot"},"answer":"D"},
  {"id":"heroes-fr-hard-106","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel terme désigne le voyage initiatique du héros selon le théoricien Joseph Campbell ?","options":{"A":"Le cycle du héros","B":"L'odyssée archétypale","C":"Le monomythe","D":"La quête symbolique"},"answer":"C"},
  {"id":"heroes-fr-hard-107","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le conte de Perrault 'La Barbe Bleue', combien d'épouses précédentes a tué le personnage ?","options":{"A":"Cinq","B":"Six","C":"Sept","D":"Quatre"},"answer":"C"},
  {"id":"heroes-fr-hard-108","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros irlandais appartient au cycle mythologique des Fianna et est célèbre pour sa sagesse acquise en goûtant le Saumon de Connaissance ?","options":{"A":"Cú Chulainn","B":"Finn Mac Cool","C":"Dagda","D":"Lugh"},"answer":"B"},
  {"id":"heroes-fr-hard-109","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans l'Iliade, quel héros troyen est le principal défenseur de la ville et frère de Pâris ?","options":{"A":"Énée","B":"Hector","C":"Priam","D":"Déiphobe"},"answer":"B"},
  {"id":"heroes-fr-hard-110","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel auteur a écrit 'Le Comte de Monte-Cristo', récit d'un héros trahi qui cherche à se venger ?","options":{"A":"Victor Hugo","B":"Stendhal","C":"Alexandre Dumas","D":"Honoré de Balzac"},"answer":"C"},
  {"id":"heroes-fr-hard-111","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie hindoue, quel héros de l'épopée Mahabharata est célèbre pour son dialogue philosophique avec Krishna ?","options":{"A":"Bhima","B":"Yudhishthira","C":"Arjuna","D":"Karna"},"answer":"C"},
  {"id":"heroes-fr-hard-112","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel élément structure le parcours du héros dans les contes selon Vladimir Propp ?","options":{"A":"Les archétypes jungiens","B":"Les fonctions narratives","C":"Les symboles initiatiques","D":"Les motifs folkloriques"},"answer":"B"},
  {"id":"heroes-fr-hard-113","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le Ramayana, quel héros part sauver son épouse Sita kidnappée par le démon Ravana ?","options":{"A":"Krishna","B":"Hanuman","C":"Rama","D":"Indra"},"answer":"C"},
  {"id":"heroes-fr-hard-114","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros africain de l'épopée mandingue fond l'empire du Mali au XIIIe siècle ?","options":{"A":"Chaka Zulu","B":"Soundiata Keïta","C":"Mansa Moussa","D":"Askia Mohamed"},"answer":"B"},
  {"id":"heroes-fr-hard-115","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie égyptienne, quel héros démembre et reconstitue le corps de son père Osiris ?","options":{"A":"Horus","B":"Seth","C":"Anubis","D":"Thot"},"answer":"A"},
  {"id":"heroes-fr-hard-116","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quelle notion désigne la faiblesse fatale d'un héros tragique dans la tradition grecque ?","options":{"A":"Catharsis","B":"Hubris","C":"Némésis","D":"Hamartia"},"answer":"D"},
  {"id":"heroes-fr-hard-117","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans 'Les Misérables', quel personnage incarne la figure du héros rédempteur qui change d'identité ?","options":{"A":"Marius","B":"L'inspecteur Javert","C":"Jean Valjean","D":"Enjolras"},"answer":"C"},
  {"id":"heroes-fr-hard-118","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros japonais de la période Edo est un samouraï errant renommé pour son invincibilité au duel ?","options":{"A":"Toyotomi Hideyoshi","B":"Miyamoto Musashi","C":"Minamoto no Yoshitsune","D":"Oda Nobunaga"},"answer":"B"},
  {"id":"heroes-fr-hard-119","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie nordique, quel héros humain tue le dragon Fáfnir et comprend le langage des oiseaux ?","options":{"A":"Beowulf","B":"Sigurd","C":"Gunnar","D":"Brynhildr"},"answer":"B"},
  {"id":"heroes-fr-hard-120","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel conte de fées met en scène un héros qui doit deviner le nom d'un lutin pour briser un sortilège ?","options":{"A":"Tom Pouce","B":"Rumpelstiltskin","C":"Hans le veinard","D":"Le vaillant petit tailleur"},"answer":"B"},
  {"id":"heroes-fr-hard-121","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans 'Don Quichotte' de Cervantes, contre quoi le héros se bat-il en croyant combattre des géants ?","options":{"A":"Des moulins à vent","B":"Des châteaux forts","C":"Des armées ennemies","D":"Des dragons de pierre"},"answer":"A"},
  {"id":"heroes-fr-hard-122","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de l'Antiquité carthaginoise traverse les Alpes avec des éléphants pour attaquer Rome ?","options":{"A":"Scipion","B":"Hamilcar","C":"Hannibal Barca","D":"Vercingétorix"},"answer":"C"},
  {"id":"heroes-fr-hard-123","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le mythe grec, quel héros attache ses compagnons sous des brebis pour s'échapper de la caverne du Cyclope ?","options":{"A":"Achille","B":"Jason","C":"Ulysse","D":"Diomède"},"answer":"C"},
  {"id":"heroes-fr-hard-124","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel concept philosophique désigne l'excès d'orgueil qui mène le héros grec à sa chute ?","options":{"A":"Anagnorisis","B":"Hybris","C":"Péripétie","D":"Catharsis"},"answer":"B"},
  {"id":"heroes-fr-hard-125","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans quelle épopée médiévale française Roland sonne-t-il du cor pour appeler Charlemagne à l'aide ?","options":{"A":"La Chanson de Guillaume","B":"Lancelot en prose","C":"La Chanson de Roland","D":"Perceval ou le Conte du Graal"},"answer":"C"},
  {"id":"heroes-fr-hard-126","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie aztèque est associé au serpent à plumes et à la création de l'humanité ?","options":{"A":"Huitzilopochtli","B":"Tlaloc","C":"Quetzalcóatl","D":"Tezcatlipoca"},"answer":"C"},
  {"id":"heroes-fr-hard-127","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le conte 'La Belle et la Bête', quel objet magique permet à la Belle de voir son père à distance ?","options":{"A":"Une bague enchantée","B":"Un miroir magique","C":"Une boule de cristal","D":"Un livre enchanté"},"answer":"B"},
  {"id":"heroes-fr-hard-128","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la littérature victorienne est un détective résolvant des crimes par pure logique, créé par Arthur Conan Doyle ?","options":{"A":"Hercule Poirot","B":"Auguste Dupin","C":"Sherlock Holmes","D":"Lord Peter Wimsey"},"answer":"C"},
  {"id":"heroes-fr-hard-129","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans l'épopée finnoise du Kalevala, quel héros forge un objet magique appelé le Sampo ?","options":{"A":"Väinämöinen","B":"Ilmarinen","C":"Lemminkäinen","D":"Kullervo"},"answer":"B"},
  {"id":"heroes-fr-hard-130","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel personnage de Molière incarne le héros séducteur sans scrupules qui défie Dieu ?","options":{"A":"Le Bourgeois Gentilhomme","B":"L'Avare","C":"Dom Juan","D":"Tartuffe"},"answer":"C"},
  {"id":"heroes-fr-hard-131","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie maorie, quel héros semi-divin attrape le soleil pour ralentir sa course et allonger les jours ?","options":{"A":"Tane","B":"Maui","C":"Tu","D":"Rongo"},"answer":"B"},
  {"id":"heroes-fr-hard-132","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie mésopotamienne combat Humbaba le gardien de la forêt de cèdres ?","options":{"A":"Enkidu seul","B":"Gilgamesh seul","C":"Gilgamesh et Enkidu ensemble","D":"Shamash"},"answer":"C"},
  {"id":"heroes-fr-hard-133","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le roman 'Vingt mille lieues sous les mers', quel héros mystérieux commande le Nautilus ?","options":{"A":"Phileas Fogg","B":"Le capitaine Haddock","C":"Le capitaine Nemo","D":"Michel Strogoff"},"answer":"C"},
  {"id":"heroes-fr-hard-134","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros chinois de l'opéra de Pékin est un singe doté de pouvoirs surnaturels et accompagne un moine en pèlerinage ?","options":{"A":"Nezha","B":"Sun Wukong","C":"Zhong Kui","D":"Erlang Shen"},"answer":"B"},
  {"id":"heroes-fr-hard-135","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans 'Cyrano de Bergerac' d'Edmond Rostand, pourquoi Cyrano n'avoue-t-il pas son amour à Roxane directement ?","options":{"A":"Il est trop timide","B":"Il a peur de la guerre","C":"Il juge son physique indigne de son amour","D":"Il aime une autre femme"},"answer":"C"},
  {"id":"heroes-fr-hard-136","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la tradition slave abat l'oiseau de feu et accomplit trois épreuves impossibles pour se marier ?","options":{"A":"Ivan Tsarévitch","B":"Koschei l'Immortel","C":"Dobrynya Nikitich","D":"Ilya Mouromets"},"answer":"A"},
  {"id":"heroes-fr-hard-137","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la tradition celtique, quel héros gallois est au centre du recueil de contes appelé le Mabinogion ?","options":{"A":"Finn Mac Cool","B":"Pryderi","C":"Cú Chulainn","D":"Bran le Béni"},"answer":"B"},
  {"id":"heroes-fr-hard-138","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel outil analytique de Vladimir Propp identifie 31 actions récurrentes dans les contes merveilleux russes ?","options":{"A":"Les mythèmes","B":"Les fonctions","C":"Les actants","D":"Les motifs"},"answer":"B"},
  {"id":"heroes-fr-hard-139","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie grecque, quel héros est changé en constellation après avoir été tué par un scorpion envoyé par la déesse Artémis ?","options":{"A":"Cassiopée","B":"Orion","C":"Persée","D":"Héraclès"},"answer":"B"},
  {"id":"heroes-fr-hard-140","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la chevalerie médiévale est le sujet du premier roman en prose de la littérature française, écrit vers 1170 ?","options":{"A":"Roland","B":"Tristan","C":"Lancelot","D":"Perceval"},"answer":"B"},
  {"id":"heroes-fr-hard-141","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans les contes amérindiens des Premières Nations, quel oiseau est souvent un héros trickster associé à la création du monde ?","options":{"A":"L'aigle","B":"Le corbeau","C":"Le colibri","D":"Le faucon"},"answer":"B"},
  {"id":"heroes-fr-hard-142","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros persan combat les forces du mal dans l'épopée du Shahnameh de Ferdousi ?","options":{"A":"Rostam","B":"Xerxès","C":"Cyrus","D":"Darius"},"answer":"A"},
  {"id":"heroes-fr-hard-143","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le conte 'Peau d'Âne' de Perrault, pourquoi la princesse quitte-t-elle le palais déguisée ?","options":{"A":"Pour trouver un prince charmant","B":"Pour fuir un mariage incestueux avec son père","C":"Pour accomplir une prophétie","D":"Pour retrouver sa mère disparue"},"answer":"B"},
  {"id":"heroes-fr-hard-144","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie sumérienne est lié à la déesse Inanna et représente le cycle des saisons par sa mort et résurrection annuelles ?","options":{"A":"Gilgamesh","B":"Dumuzi","C":"Enlil","D":"Enki"},"answer":"B"},
  {"id":"heroes-fr-hard-145","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans quel roman de Jules Verne un héros fait le tour du monde en quatre-vingts jours pour gagner un pari ?","options":{"A":"Michel Strogoff","B":"Voyage au centre de la Terre","C":"Le Tour du monde en quatre-vingts jours","D":"De la Terre à la Lune"},"answer":"C"},
  {"id":"heroes-fr-hard-146","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la tradition polynésienne hame le fond de l'océan pour repêcher les îles du Pacifique ?","options":{"A":"Tane","B":"Maui","C":"Tangaroa","D":"Hiro"},"answer":"B"},
  {"id":"heroes-fr-hard-147","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le conte de Madame d'Aulnoy 'L'Oiseau Bleu', en quel animal le roi est-il transformé par une fée maléfique ?","options":{"A":"Un corbeau","B":"Un cygne","C":"Un oiseau bleu","D":"Un faucon"},"answer":"C"},
  {"id":"heroes-fr-hard-148","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de l'Inde ancienne est un archer légendaire, héros du Mahabharata, dont le nom signifie 'l'argenté' ?","options":{"A":"Bhima","B":"Arjuna","C":"Drona","D":"Karna"},"answer":"B"},
  {"id":"heroes-fr-hard-149","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel concept désigne la transformation intérieure du héros qui revient changé de son voyage initiatique ?","options":{"A":"La métamorphose","B":"La révélation","C":"L'anagnorisis","D":"La rédemption"},"answer":"C"},
  {"id":"heroes-fr-hard-150","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la tradition orale africaine, quel héros de l'empire Songhaï est célébré dans l'épopée 'Askia Mohammad' pour sa foi et ses conquêtes ?","options":{"A":"Soundiata","B":"Askia le Grand","C":"Chaka","D":"Behanzin"},"answer":"B"},
  {"id":"heroes-fr-hard-151","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la littérature espagnole, commandant d'une armée chrétienne, est au centre du 'Poème du Cid' ?","options":{"A":"Don Quichotte","B":"Rodrigue de Bivar dit El Cid","C":"Ferdinand le Catholique","D":"Rodrigo Díaz de Vivar dit Fierabras"},"answer":"B"},
  {"id":"heroes-fr-hard-152","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie babylonienne, quel héros combat le chaos primordial incarné par la déesse-dragon Tiamat ?","options":{"A":"Enkidu","B":"Gilgamesh","C":"Marduk","D":"Anu"},"answer":"C"},
  {"id":"heroes-fr-hard-153","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel auteur belge a créé le personnage de Tintin en 1929 ?","options":{"A":"Maurice de Bévère dit Morris","B":"Edgar P. Jacobs","C":"Georges Remi dit Hergé","D":"Raymond Macherot"},"answer":"C"},
  {"id":"heroes-fr-hard-154","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie grecque, quel héros chante si bien qu'il charme les pierres et les bêtes sauvages ?","options":{"A":"Apollon","B":"Arion","C":"Orphée","D":"Marsyas"},"answer":"C"},
  {"id":"heroes-fr-hard-155","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel personnage féminin de la mythologie grecque est la première femme créée par les dieux et détient une jarre contenant tous les maux du monde ?","options":{"A":"Hécate","B":"Pandore","C":"Circé","D":"Médée"},"answer":"B"},
  {"id":"heroes-fr-hard-156","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le roman 'L'Île au trésor' de Stevenson, quel personnage est à la fois cuisinier et pirate redouté ?","options":{"A":"Le Capitaine Flint","B":"Long John Silver","C":"Billy Bones","D":"Ben Gunn"},"answer":"B"},
  {"id":"heroes-fr-hard-157","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie aztèque est le dieu du soleil et de la guerre, né adulte et en armes d'une déesse-terre ?","options":{"A":"Quetzalcóatl","B":"Tlaloc","C":"Huitzilopochtli","D":"Xipe Totec"},"answer":"C"},
  {"id":"heroes-fr-hard-158","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le conte 'Barbe-Bleue', quel objet la femme reçoit-elle de son mari et qu'elle est interdite d'utiliser ?","options":{"A":"Un coffret de bijoux","B":"Une clé qui ouvre une chambre interdite","C":"Un miroir enchanté","D":"Un anneau de vœux"},"answer":"B"},
  {"id":"heroes-fr-hard-159","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie grecque est fils de Pélée et de la néréide Thétis, et connu pour sa vitesse exceptionnelle ?","options":{"A":"Patrocle","B":"Ajax","C":"Achille","D":"Diomède"},"answer":"C"},
  {"id":"heroes-fr-hard-160","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le 'Beowulf', contre combien de monstres différents le héros combat-il successivement ?","options":{"A":"Deux","B":"Trois","C":"Quatre","D":"Cinq"},"answer":"B"},
  {"id":"heroes-fr-hard-161","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie celtique irlandaise est un semidivin guerrier du cycle d'Ulster dont l'éducation fut confiée à des druides ?","options":{"A":"Finn Mac Cool","B":"Conchobar","C":"Cú Chulainn","D":"Fergus Mac Róich"},"answer":"C"},
  {"id":"heroes-fr-hard-162","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la littérature du Moyen Âge, quel terme désigne les récits de chevalerie centrés sur Charlemagne et ses paladins ?","options":{"A":"Cycle breton","B":"Chanson de geste","C":"Roman courtois","D":"Lai breton"},"answer":"B"},
  {"id":"heroes-fr-hard-163","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la bande dessinée franco-belge est un jeune reporter qui voyage dans la Lune bien avant les astronautes réels ?","options":{"A":"Astérix","B":"Lucky Luke","C":"Spirou","D":"Tintin"},"answer":"D"},
  {"id":"heroes-fr-hard-164","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le conte 'Les Douze Frères' des frères Grimm, comment la sœur sauve-t-elle ses frères transformés en corbeaux ?","options":{"A":"En les embrassant chacun","B":"En restant silencieuse pendant six ans et en cousant des chemises d'orties","C":"En combattant la sorcière","D":"En résolvant trois énigmes"},"answer":"B"},
  {"id":"heroes-fr-hard-165","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie nordique est aveugle et tue accidentellement Baldr avec une branche de gui manipulée par Loki ?","options":{"A":"Tyr","B":"Höðr","C":"Víðarr","D":"Váli"},"answer":"B"},
  {"id":"heroes-fr-hard-166","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la tradition de contes oraux africains, quel animal rusé joue souvent le rôle du héros trickster au Sénégal et en Gambie ?","options":{"A":"Le lion","B":"L'éléphant","C":"Le lièvre","D":"La hyène"},"answer":"C"},
  {"id":"heroes-fr-hard-167","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de Voltaire parcourt le monde pour trouver que 'tout va pour le mieux dans le meilleur des mondes possibles' ?","options":{"A":"Micromégas","B":"Zadig","C":"Candide","D":"L'Ingénu"},"answer":"C"},
  {"id":"heroes-fr-hard-168","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie grecque, quel héros délivre Andromède en tuant un monstre marin avec la tête de Méduse ?","options":{"A":"Bellérophon","B":"Persée","C":"Thésée","D":"Jason"},"answer":"B"},
  {"id":"heroes-fr-hard-169","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel auteur a écrit 'Les Trois Mousquetaires', roman d'aventures mettant en scène d'Artagnan ?","options":{"A":"Victor Hugo","B":"Gustave Flaubert","C":"Alexandre Dumas","D":"Prosper Mérimée"},"answer":"C"},
  {"id":"heroes-fr-hard-170","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie grecque, quelle héroïne refuse de se marier tant qu'elle n'est pas battue à la course, et sera vaincue par la ruse des pommes d'or ?","options":{"A":"Hécube","B":"Atalante","C":"Hélène","D":"Clytemnestre"},"answer":"B"},
  {"id":"heroes-fr-hard-171","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de conte germanique vend son ombre au diable et perd progressivement son identité dans l'œuvre de Chamisso ?","options":{"A":"Faust","B":"Peter Schlemihl","C":"Till l'Espiègle","D":"Reineke le Renard"},"answer":"B"},
  {"id":"heroes-fr-hard-172","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la tradition épique médiévale, quel héros russe (bogatyr) est paralysé pendant 30 ans avant de recevoir ses pouvoirs légendaires ?","options":{"A":"Dobrynya Nikitich","B":"Aliocha Popovitch","C":"Ilya Mouromets","D":"Mikula Selianinovich"},"answer":"C"},
  {"id":"heroes-fr-hard-173","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le conte 'Riquet à la houppe' de Perrault, quel don le héros offre-t-il à la princesse en échange de sa main ?","options":{"A":"La beauté éternelle","B":"L'intelligence","C":"Le courage","D":"La richesse"},"answer":"B"},
  {"id":"heroes-fr-hard-174","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie grecque est fils de Poséidon, tue le monstre Méduse et délivre Andromède ?","options":{"A":"Bellérophon","B":"Persée","C":"Héraclès","D":"Thésée"},"answer":"B"},
  {"id":"heroes-fr-hard-175","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans 'Robin des Bois', quel lieu sacré réunit Robin et ses compagnons dans la forêt de Sherwood ?","options":{"A":"Le chêne royal","B":"Le grand chêne de Merlin","C":"Le chêne Major Oak","D":"La croix des outlaws"},"answer":"C"},
  {"id":"heroes-fr-hard-176","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de l'Antiquité gauloise est présenté dans les sources romaines comme le chef de la résistance contre Jules César ?","options":{"A":"Ambiorix","B":"Brennus","C":"Vercingétorix","D":"Viriathus"},"answer":"C"},
  {"id":"heroes-fr-hard-177","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie grecque, quel héros construit le Cheval de Troie pour permettre aux Grecs de pénétrer dans la ville ?","options":{"A":"Achille","B":"Ménélas","C":"Ulysse","D":"Diomède"},"answer":"C"},
  {"id":"heroes-fr-hard-178","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros mythique de l'ancienne Mésopotamie cherche la plante de l'immortalité au fond de l'océan mais la perd à cause d'un serpent ?","options":{"A":"Marduk","B":"Enkidu","C":"Gilgamesh","D":"Shamash"},"answer":"C"},
  {"id":"heroes-fr-hard-179","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans 'Les Aventures de Tom Sawyer' de Mark Twain, qui est le meilleur ami de Tom ?","options":{"A":"Joe Harper","B":"Huckleberry Finn","C":"Sid Sawyer","D":"Injun Joe"},"answer":"B"},
  {"id":"heroes-fr-hard-180","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie égyptienne guide les âmes des morts vers l'au-delà et pèse leur cœur contre une plume ?","options":{"A":"Osiris","B":"Thot","C":"Horus","D":"Anubis"},"answer":"D"},
  {"id":"heroes-fr-hard-181","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans 'Le Petit Prince' de Saint-Exupéry, de quelle planète vient le héros ?","options":{"A":"L'astéroïde B-611","B":"L'astéroïde B-612","C":"L'astéroïde B-613","D":"L'astéroïde A-612"},"answer":"B"},
  {"id":"heroes-fr-hard-182","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de l'épopée grecque participe à la guerre de Troie malgré lui, après avoir feint la folie pour éviter d'y aller ?","options":{"A":"Achille","B":"Ulysse","C":"Diomède","D":"Ménélas"},"answer":"B"},
  {"id":"heroes-fr-hard-183","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la tradition des contes de fées, quel élément symbolise souvent l'épreuve finale que le héros doit surmonter pour accéder à la maturité ?","options":{"A":"Le dragon","B":"L'enchantement","C":"Le mariage","D":"La forêt obscure"},"answer":"D"},
  {"id":"heroes-fr-hard-184","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel auteur français du XVIIe siècle a écrit 'Contes de ma mère l'Oye', recueil incluant Cendrillon et Le Chat Botté ?","options":{"A":"Jean de La Fontaine","B":"Madame d'Aulnoy","C":"Charles Perrault","D":"Madame de Ségur"},"answer":"C"},
  {"id":"heroes-fr-hard-185","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie grecque vole le feu aux dieux pour le donner aux hommes et est condamné à être enchaîné à un rocher ?","options":{"A":"Héphaïstos","B":"Épiméthée","C":"Dédale","D":"Prométhée"},"answer":"D"},
  {"id":"heroes-fr-hard-186","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans 'Gargantua' de Rabelais, quel héros géant incarne l'idéal humaniste de la Renaissance par sa soif de savoir ?","options":{"A":"Pantagruel","B":"Panurge","C":"Gargantua","D":"Frère Jean"},"answer":"C"},
  {"id":"heroes-fr-hard-187","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros du roman policier belge est un détective à la moustache soignée et aux 'petites cellules grises' ?","options":{"A":"Nestor Burma","B":"Commissaire Maigret","C":"Hercule Poirot","D":"San-Antonio"},"answer":"C"},
  {"id":"heroes-fr-hard-188","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie sumérienne, quelle déesse descend aux Enfers et doit laisser son époux Dumuzi pour en revenir ?","options":{"A":"Ishtar","B":"Ninhursag","C":"Inanna","D":"Ereshkigal"},"answer":"C"},
  {"id":"heroes-fr-hard-189","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de l'Odyssée est le fils d'Ulysse qui part à la recherche de son père absent ?","options":{"A":"Icare","B":"Télémaque","C":"Oreste","D":"Pylade"},"answer":"B"},
  {"id":"heroes-fr-hard-190","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la tradition chevaleresque, quel idéal moral guide le comportement du chevalier parfait ?","options":{"A":"La prouesse et la générosité","B":"La bravoure et la richesse","C":"La courtoisie et la piété","D":"La prouesse, la loyauté et la courtoisie"},"answer":"D"},
  {"id":"heroes-fr-hard-191","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros fictif français est un as de l'aviation de la Première Guerre mondiale dans une série de romans populaires ?","options":{"A":"Biggles","B":"L'Escadrille des As","C":"L'aviateur masqué","D":"L'As des As"},"answer":"D"},
  {"id":"heroes-fr-hard-192","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie grecque, quelle créature mi-homme mi-taureau est enfermée dans le Labyrinthe de Crète ?","options":{"A":"Le Sphinx","B":"Le Minotaure","C":"La Chimère","D":"Cerbère"},"answer":"B"},
  {"id":"heroes-fr-hard-193","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de l'épopée irlandaise est condamné à ne manger que la viande des chiens après avoir violé son geis ?","options":{"A":"Finn Mac Cool","B":"Conchobar","C":"Cú Chulainn","D":"Diarmuid"},"answer":"C"},
  {"id":"heroes-fr-hard-194","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans le conte 'Le Vaillant Petit Tailleur' des frères Grimm, combien de mouches le héros tue-t-il d'un seul coup ?","options":{"A":"Cinq","B":"Six","C":"Sept","D":"Huit"},"answer":"C"},
  {"id":"heroes-fr-hard-195","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de la mythologie nordique est destiné à survivre au Ragnarök et à rebâtir le monde ?","options":{"A":"Thor","B":"Baldr","C":"Víðarr","D":"Freyr"},"answer":"C"},
  {"id":"heroes-fr-hard-196","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans quel pays d'origine se situe l'épopée de Sundiata, héros fondateur d'un grand empire médiéval ?","options":{"A":"Ghana","B":"Mali","C":"Sénégal","D":"Côte d'Ivoire"},"answer":"B"},
  {"id":"heroes-fr-hard-197","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel héros de Jules Verne traverse la Sibérie pour porter un message au tsar pendant une rébellion ?","options":{"A":"Phileas Fogg","B":"Capitaine Nemo","C":"Michel Strogoff","D":"Robur le Conquérant"},"answer":"C"},
  {"id":"heroes-fr-hard-198","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie germanique, quel héros réveille la Walkyrie Brünnhilde endormie derrière un cercle de flammes ?","options":{"A":"Gunnar","B":"Sigurd","C":"Hagen","D":"Attila"},"answer":"B"},
  {"id":"heroes-fr-hard-199","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Quel auteur allemand a écrit 'Till l'Espiègle', récit de facéties d'un héros populaire de la Renaissance ?","options":{"A":"Thomas Mann","B":"Herman Bote","C":"Johann Wolfgang von Goethe","D":"Friedrich Schiller"},"answer":"B"},
  {"id":"heroes-fr-hard-200","category":"heros","subcategory":None,"locale":"fr","difficulty":"hard","question":"Dans la mythologie grecque, quelle héroïne tue son propre mari et ses enfants après avoir été répudiée, dans la tragédie d'Euripide ?","options":{"A":"Électre","B":"Hécube","C":"Médée","D":"Clytemnestre"},"answer":"C"},
]

PATH = Path(__file__).parent.parent / "src/data/questions/fr/heroes.json"
with open(PATH) as f:
    data = json.load(f)

existing_ids = {q["id"] for q in data["questions"]}
existing_q = {q["question"].strip() for q in data["questions"]}

added = 0
for q in NEW_QUESTIONS:
    if q["id"] not in existing_ids and q["question"].strip() not in existing_q:
        data["questions"].append(q)
        added += 1

print(f"Ajoutées: {added} | Total: {len(data['questions'])}")

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write("\n")
