"""Ajoute 126 questions EN heroes FLE (49 easy + 77 hard) pour atteindre 600."""
import json, random
from pathlib import Path

NEW_QUESTIONS = [
  # === EASY (49) ===
  {"id":"hero-en-0601","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which princess has hair so long she lets it down from a tower so a visitor can climb up?","options":{"A":"Snow White","B":"Rapunzel","C":"Cinderella","D":"Sleeping Beauty"},"answer":"B"},
  {"id":"hero-en-0602","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Gaston is the villain who tries to force a young woman who loves reading to marry him. What is her name?","options":{"A":"Cinderella","B":"Aurora","C":"Belle","D":"Ariel"},"answer":"C"},
  {"id":"hero-en-0603","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which brave girl cuts her hair, disguises herself as a soldier, and joins the army in her father's place?","options":{"A":"Moana","B":"Mulan","C":"Merida","D":"Pocahontas"},"answer":"B"},
  {"id":"hero-en-0604","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A kind girl is given glass slippers by a fairy godmother and must leave the ball before midnight. Who is she?","options":{"A":"Belle","B":"Aurora","C":"Cinderella","D":"Snow White"},"answer":"C"},
  {"id":"hero-en-0605","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which small boy is raised by wolves in the jungle and befriends a bear called Baloo?","options":{"A":"Peter Pan","B":"Tarzan","C":"Mowgli","D":"Pinocchio"},"answer":"C"},
  {"id":"hero-en-0606","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A puppet made of wood dreams of becoming a real boy. What is his name?","options":{"A":"Gepetto","B":"Jiminy Cricket","C":"Figaro","D":"Pinocchio"},"answer":"D"},
  {"id":"hero-en-0607","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which young mermaid collects human objects and longs to live on land?","options":{"A":"Thumbelina","B":"Ariel","C":"Marina","D":"Pearl"},"answer":"B"},
  {"id":"hero-en-0608","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A boy who never grows up lives on an island called Neverland. What is his name?","options":{"A":"Wendy","B":"Captain Hook","C":"Tinker Bell","D":"Peter Pan"},"answer":"D"},
  {"id":"hero-en-0609","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which toy cowboy is the leader of his friends in a child's bedroom?","options":{"A":"Buzz Lightyear","B":"Woody","C":"Rex","D":"Hamm"},"answer":"B"},
  {"id":"hero-en-0610","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Who is the young lion cub who must take his rightful place as king after his father Mufasa is killed?","options":{"A":"Simba","B":"Nala","C":"Mufasa","D":"Timon"},"answer":"A"},
  {"id":"hero-en-0611","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which superhero wears a red and blue suit and can shoot webs from his wrists?","options":{"A":"Batman","B":"Iron Man","C":"Spider-Man","D":"Superman"},"answer":"C"},
  {"id":"hero-en-0612","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A young girl falls down a rabbit hole and discovers a land full of strange creatures. What is her name?","options":{"A":"Dorothy","B":"Wendy","C":"Alice","D":"Lucy"},"answer":"C"},
  {"id":"hero-en-0613","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which hero travels with three friends down a yellow brick road to meet the Wizard of Oz?","options":{"A":"Alice","B":"Dorothy","C":"Wendy","D":"Gretel"},"answer":"B"},
  {"id":"hero-en-0614","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A clever cat wearing boots helps his poor master become rich and marry a princess. What is the cat called?","options":{"A":"Felix the Cat","B":"Tom","C":"Puss in Boots","D":"The Cheshire Cat"},"answer":"C"},
  {"id":"hero-en-0615","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which young hobbit unexpectedly goes on an adventure with thirteen dwarves and a wizard?","options":{"A":"Frodo Baggins","B":"Samwise Gamgee","C":"Bilbo Baggins","D":"Pippin"},"answer":"C"},
  {"id":"hero-en-0616","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which princess is under a sleeping curse that can only be broken by true love's kiss?","options":{"A":"Rapunzel","B":"Ariel","C":"Belle","D":"Aurora"},"answer":"D"},
  {"id":"hero-en-0617","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A small boy is left home alone and must defend his house against two clumsy burglars. What is his name?","options":{"A":"Kevin McCallister","B":"Macaulay Culkin","C":"Timmy Turner","D":"Richie Rich"},"answer":"A"},
  {"id":"hero-en-0618","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which brave Viking boy trains a dragon he names Toothless?","options":{"A":"Astrid","B":"Snotlout","C":"Fishlegs","D":"Hiccup"},"answer":"D"},
  {"id":"hero-en-0619","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A young girl with a bow and arrow volunteers to take her sister's place in a deadly competition. Who is she?","options":{"A":"Merida","B":"Katniss Everdeen","C":"Tris Prior","D":"Moana"},"answer":"B"},
  {"id":"hero-en-0620","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which character is a bear who lives in Paddington Station and loves marmalade sandwiches?","options":{"A":"Winnie-the-Pooh","B":"Baloo","C":"Paddington Bear","D":"Rupert Bear"},"answer":"C"},
  {"id":"hero-en-0621","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A young girl named Chihiro must work in a magical bathhouse to rescue her parents, who have been turned into pigs. What is the name of this film?","options":{"A":"My Neighbor Totoro","B":"Spirited Away","C":"Princess Mononoke","D":"Nausicaä"},"answer":"B"},
  {"id":"hero-en-0622","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which legendary archer steals from the rich and gives to the poor in Sherwood Forest?","options":{"A":"William Tell","B":"Legolas","C":"Robin Hood","D":"Green Arrow"},"answer":"C"},
  {"id":"hero-en-0623","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A brave Scottish princess refuses to marry and accidentally turns her mother into a bear. What is her name?","options":{"A":"Fiona","B":"Moana","C":"Elsa","D":"Merida"},"answer":"D"},
  {"id":"hero-en-0624","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which young sailor discovers that her island ancestors were once great voyagers and must sail across the ocean to save her people?","options":{"A":"Mulan","B":"Pocahontas","C":"Moana","D":"Merida"},"answer":"C"},
  {"id":"hero-en-0625","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A girl with ice powers accidentally freezes her kingdom and must learn to control her gift. What is her name?","options":{"A":"Anna","B":"Elsa","C":"Olaf","D":"Kristoff"},"answer":"B"},
  {"id":"hero-en-0626","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which young boy befriends an extraterrestrial visitor and helps him phone home?","options":{"A":"Elliott","B":"Michael","C":"Gertie","D":"Greg"},"answer":"A"},
  {"id":"hero-en-0627","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A very small girl the size of a thumb is carried away by a frog and eventually flies to a warm land with sparrows. What is she called?","options":{"A":"Tinker Bell","B":"Thumbelina","C":"Tinkerbell","D":"Nuala"},"answer":"B"},
  {"id":"hero-en-0628","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which young shepherd boy defeats a giant warrior named Goliath using only a slingshot?","options":{"A":"Solomon","B":"Joshua","C":"David","D":"Samson"},"answer":"C"},
  {"id":"hero-en-0629","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A small blue robot cleans an abandoned Earth and falls in love with a sleek white robot. What is his name?","options":{"A":"R2-D2","B":"WALL-E","C":"Baymax","D":"EVE"},"answer":"B"},
  {"id":"hero-en-0630","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which hero wears a red cape and uses a magic hammer to protect people from danger?","options":{"A":"Iron Man","B":"Captain America","C":"Hulk","D":"Thor"},"answer":"D"},
  {"id":"hero-en-0631","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A young ratatouille-loving rat dreams of becoming a great chef in Paris. What is his name?","options":{"A":"Emile","B":"Gusteau","C":"Remy","D":"Linguini"},"answer":"C"},
  {"id":"hero-en-0632","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which young man pulls a sword from a stone and becomes the rightful king of England?","options":{"A":"Merlin","B":"Lancelot","C":"Gawain","D":"Arthur"},"answer":"D"},
  {"id":"hero-en-0633","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A young Polynesian demigod can shape-shift and uses a giant magical fishhook. What is his name?","options":{"A":"Maui","B":"Moana","C":"Tamatoa","D":"Te Fiti"},"answer":"A"},
  {"id":"hero-en-0634","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which hero is a clownfish who crosses the entire ocean to find his son?","options":{"A":"Dory","B":"Bruce","C":"Marlin","D":"Gill"},"answer":"C"},
  {"id":"hero-en-0635","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A friendly ghost who wants to make friends instead of scaring people. What is his name?","options":{"A":"Slimer","B":"Casper","C":"Boo","D":"Spooky"},"answer":"B"},
  {"id":"hero-en-0636","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which young wizard attends Hogwarts School and is famous for a lightning bolt scar on his forehead?","options":{"A":"Neville Longbottom","B":"Ron Weasley","C":"Draco Malfoy","D":"Harry Potter"},"answer":"D"},
  {"id":"hero-en-0637","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A boy raised by gorillas grows up to become a brave protector of the jungle. What is his name?","options":{"A":"Mowgli","B":"Tarzan","C":"George","D":"Kala"},"answer":"B"},
  {"id":"hero-en-0638","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which small creature lives in a cozy hole in the ground and likes comfort, but is convinced to go on an adventure by a wizard?","options":{"A":"Frodo Baggins","B":"Samwise Gamgee","C":"Bilbo Baggins","D":"Gandalf"},"answer":"C"},
  {"id":"hero-en-0639","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A young girl goes through a magic wardrobe and discovers the land of Narnia, where animals can talk. What is her name?","options":{"A":"Susan Pevensie","B":"Lucy Pevensie","C":"Edmund Pevensie","D":"Peter Pevensie"},"answer":"B"},
  {"id":"hero-en-0640","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which superhero can stretch his body into any shape and has a family of superheroes?","options":{"A":"The Hulk","B":"Mr. Incredible","C":"Mr. Fantastic","D":"Elastigirl"},"answer":"C"},
  {"id":"hero-en-0641","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A young boy finds a golden ticket and wins a tour of a magical chocolate factory. What is his name?","options":{"A":"Augustus Gloop","B":"Violet Beauregarde","C":"Mike Teavee","D":"Charlie Bucket"},"answer":"D"},
  {"id":"hero-en-0642","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which hero is a wooden toy soldier who defends a little girl from the Mouse King on Christmas Eve?","options":{"A":"The Tin Soldier","B":"The Nutcracker","C":"Jack-in-the-box","D":"The Scarecrow"},"answer":"B"},
  {"id":"hero-en-0643","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A brave mouse wears a tiny suit of armour and goes on adventures rescuing other small creatures. What is his name?","options":{"A":"Stuart Little","B":"Reepicheep","C":"Despereaux","D":"Danger Mouse"},"answer":"C"},
  {"id":"hero-en-0644","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which young African king must stand up to his evil uncle to reclaim his kingdom?","options":{"A":"Simba","B":"Mufasa","C":"Kovu","D":"Kiara"},"answer":"A"},
  {"id":"hero-en-0645","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A young boy named Geppetto carves a puppet that magically comes to life. What does he wish for his creation?","options":{"A":"To become a great magician","B":"To become a real boy","C":"To become a great sailor","D":"To become a prince"},"answer":"B"},
  {"id":"hero-en-0646","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which hero is a tiny girl born from a flower who must find her own fairy people?","options":{"A":"Tinker Bell","B":"Thumbelina","C":"Silvermist","D":"Rosetta"},"answer":"B"},
  {"id":"hero-en-0647","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A young prince must break a curse that has turned him into a beast by learning to love and be loved in return. Who is he?","options":{"A":"Eric","B":"Adam (the Beast)","C":"Phillip","D":"Naveen"},"answer":"B"},
  {"id":"hero-en-0648","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"Which young hero is chosen to carry a magical ring on a long journey to destroy it in a volcano?","options":{"A":"Bilbo Baggins","B":"Gandalf","C":"Frodo Baggins","D":"Aragorn"},"answer":"C"},
  {"id":"hero-en-0649","category":"heroes","subcategory":None,"locale":"en","difficulty":"easy","question":"A boy named Max is sent to his room and imagines sailing to a land ruled by wild creatures. What are they called?","options":{"A":"Wild Things","B":"Monsters","C":"Beasts","D":"Creatures"},"answer":"A"},
  # === HARD (77) ===
  {"id":"hero-en-0650","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In Perrault's 'Bluebeard', the heroine's brothers arrive just in time to save her from her husband. What are they?","options":{"A":"Knights","B":"Soldiers","C":"Hunters","D":"Musketeers"},"answer":"C"},
  {"id":"hero-en-0651","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Cyrano de Bergerac secretly writes love letters for his friend Christian to send to Roxane. What is Cyrano's great talent?","options":{"A":"Sword fighting only","B":"Poetry and eloquence","C":"Music and song","D":"Painting and art"},"answer":"B"},
  {"id":"hero-en-0652","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"The hero Gawain accepts a beheading challenge from a Green Knight. This story belongs to which legendary cycle?","options":{"A":"The Song of Roland","B":"The Trojan cycle","C":"The Arthurian legend","D":"The Norse sagas"},"answer":"C"},
  {"id":"hero-en-0653","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In the original tale by Madame de Beaumont, what does Beauty's father do that triggers the whole story?","options":{"A":"He sells Beauty to the Beast","B":"He picks a rose from the Beast's garden","C":"He trespasses in the Beast's castle","D":"He steals the Beast's golden cup"},"answer":"B"},
  {"id":"hero-en-0654","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Jean Valjean, the reformed hero of a famous novel, was originally imprisoned for nineteen years. What was his crime?","options":{"A":"Theft of a loaf of bread","B":"Murder","C":"Fraud","D":"Desertion from the army"},"answer":"A"},
  {"id":"hero-en-0655","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Arsène Lupin is known as a 'gentleman thief'. Which author created this character?","options":{"A":"Jules Verne","B":"Alexandre Dumas","C":"Maurice Leblanc","D":"Gaston Leroux"},"answer":"C"},
  {"id":"hero-en-0656","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In the legend of Roland, at which battle does the hero die defending Charlemagne's rearguard?","options":{"A":"The Battle of Tours","B":"The Battle of Roncevaux Pass","C":"The Battle of Hastings","D":"The Battle of Poitiers"},"answer":"B"},
  {"id":"hero-en-0657","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"The story of 'Tristan and Iseult' is a tragic medieval romance. What makes Tristan and Iseult fall in love?","options":{"A":"A magic spell cast by a druid","B":"A love potion they accidentally drink","C":"A vision Tristan has in battle","D":"Iseult saves Tristan's life"},"answer":"B"},
  {"id":"hero-en-0658","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In Molière's play, Dom Juan is a nobleman who seduces and abandons women. What ultimately punishes him?","options":{"A":"The king's justice","B":"A duel with an angry father","C":"The statue of the Commander dragging him to hell","D":"He is imprisoned by the Church"},"answer":"C"},
  {"id":"hero-en-0659","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Phileas Fogg bets he can travel around the world in how many days?","options":{"A":"Sixty","B":"Seventy","C":"Eighty","D":"Ninety"},"answer":"C"},
  {"id":"hero-en-0660","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In the Arthurian legends, which knight achieves the quest for the Holy Grail because of his perfect purity?","options":{"A":"Lancelot","B":"Gawain","C":"Percival","D":"Galahad"},"answer":"D"},
  {"id":"hero-en-0661","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"The hero Odysseus resists the Sirens by having his sailors plug their ears and tie him to the mast. What makes Sirens dangerous?","options":{"A":"Their hypnotic gaze","B":"Their enchanting singing","C":"Their poisonous breath","D":"Their ability to shapeshift"},"answer":"B"},
  {"id":"hero-en-0662","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Captain Nemo commands the submarine Nautilus in a novel by Jules Verne. What does 'Nemo' mean in Latin?","options":{"A":"Shadow","B":"Sea","C":"No one","D":"Wanderer"},"answer":"C"},
  {"id":"hero-en-0663","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'The Count of Monte Cristo', Edmond Dantès escapes from the Château d'If prison by hiding in what?","options":{"A":"A laundry basket","B":"A wine barrel","C":"A dead prisoner's burial sack","D":"A supply boat"},"answer":"C"},
  {"id":"hero-en-0664","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Hercules must complete twelve labours. Which of these is NOT one of them?","options":{"A":"Slaying the Nemean Lion","B":"Cleaning the Augean stables","C":"Stealing the Golden Fleece","D":"Capturing the Erymanthian Boar"},"answer":"C"},
  {"id":"hero-en-0665","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In Andersen's tale, the Little Mermaid's voice is taken by the Sea Witch in exchange for legs. What does she use her voice for?","options":{"A":"Her singing voice is her greatest power","B":"She trades it to get legs and walk on land","C":"The witch steals it as punishment","D":"She gives it to save her sisters"},"answer":"B"},
  {"id":"hero-en-0666","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"The three musketeers' motto 'All for one, one for all' appears in a novel by Alexandre Dumas. What is d'Artagnan's home region?","options":{"A":"Provence","B":"Burgundy","C":"Gascony","D":"Normandy"},"answer":"C"},
  {"id":"hero-en-0667","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Which hero of ancient Mesopotamia is two-thirds divine and one-third mortal, according to the epic?","options":{"A":"Marduk","B":"Enkidu","C":"Gilgamesh","D":"Shamash"},"answer":"C"},
  {"id":"hero-en-0668","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Beowulf fights three monsters across his lifetime. The last one, which kills him, is a fire-breathing creature. What is it?","options":{"A":"A sea serpent","B":"A dragon","C":"A giant wolf","D":"A demon"},"answer":"B"},
  {"id":"hero-en-0669","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Perseus uses a shiny shield as a mirror to avoid looking directly at Medusa. Why is looking at Medusa dangerous?","options":{"A":"Her screech causes deafness","B":"Her gaze turns people to stone","C":"Her breath is poisonous","D":"Her eyes cause madness"},"answer":"B"},
  {"id":"hero-en-0670","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Sindbad the Sailor makes seven voyages. In which collection of tales do his adventures appear?","options":{"A":"The Decameron","B":"The Canterbury Tales","C":"One Thousand and One Nights","D":"Aesop's Fables"},"answer":"C"},
  {"id":"hero-en-0671","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Peau d'Âne' by Perrault, a princess flees her father's palace wearing a donkey skin. What does the donkey skin produce?","options":{"A":"It grants her invisibility","B":"It produces gold coins","C":"It allows her to shapeshift","D":"It protects her from the cold"},"answer":"B"},
  {"id":"hero-en-0672","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"The hero Jason leads a crew called the Argonauts. What is their quest?","options":{"A":"To rescue Helen of Troy","B":"To retrieve the Golden Fleece","C":"To slay the Minotaur","D":"To find the Garden of Hesperides"},"answer":"B"},
  {"id":"hero-en-0673","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Theseus volunteers to go to Crete as one of the tribute victims. He promises to change his ship's sails if he survives. What color are the sails of a victorious return meant to be?","options":{"A":"White","B":"Red","C":"Gold","D":"Blue"},"answer":"A"},
  {"id":"hero-en-0674","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Rumpelstiltskin', the miller's daughter must spin straw into gold. What does she finally offer Rumpelstiltskin on the third night?","options":{"A":"Her golden necklace","B":"Her firstborn child","C":"Her ring","D":"Her voice"},"answer":"B"},
  {"id":"hero-en-0675","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Sundiata Keïta, the hero of a West African epic, could not walk as a child. What miraculous event marks his rise?","options":{"A":"He defeats a giant lion alone","B":"He stands up and walks to retrieve an iron rod","C":"He speaks his first words at age seven","D":"He receives a divine sword from a river spirit"},"answer":"B"},
  {"id":"hero-en-0676","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In Norse mythology, Sigurd kills the dragon Fafnir and tastes its blood. What power does this give him?","options":{"A":"Invincibility in battle","B":"Understanding the language of birds","C":"Immortality","D":"Control over fire"},"answer":"B"},
  {"id":"hero-en-0677","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Scheherazade tells stories to a king every night to delay her own execution. For how many nights does she continue?","options":{"A":"Seven hundred","B":"Nine hundred","C":"One thousand","D":"One thousand and one"},"answer":"D"},
  {"id":"hero-en-0678","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Don Quixote', the hero mistakes windmills for giants. What does his squire Sancho Panza represent in contrast to Don Quixote?","options":{"A":"Evil and greed","B":"Practical common sense","C":"Cowardice","D":"Noble idealism"},"answer":"B"},
  {"id":"hero-en-0679","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In the legend of William Tell, he is forced to shoot an apple from his son's head as punishment. Who forces him to do this?","options":{"A":"The Emperor Maximilian","B":"The bailiff Gessler","C":"The Duke of Habsburg","D":"The Bishop of Constance"},"answer":"B"},
  {"id":"hero-en-0680","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Achilles is nearly invulnerable because his mother dipped him in the River Styx. Which part of his body was not protected?","options":{"A":"His shoulder","B":"His wrist","C":"His heel","D":"His knee"},"answer":"C"},
  {"id":"hero-en-0681","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'The Valiant Little Tailor' by the Brothers Grimm, what does the tailor embroider on his belt after his feat?","options":{"A":"'Seven at one blow'","B":"'Ten at one strike'","C":"'Five at once'","D":"'Seven in one stroke'"},"answer":"A"},
  {"id":"hero-en-0682","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"The hero Rama rescues his wife Sita from the demon Ravana in an ancient epic. Which monkey-god helps him by building a bridge to Lanka?","options":{"A":"Ganesh","B":"Arjuna","C":"Hanuman","D":"Krishna"},"answer":"C"},
  {"id":"hero-en-0683","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In Celtic mythology, Cú Chulainn's real name was Sétanta. How did he earn his new name?","options":{"A":"He killed a king's champion in a duel","B":"He slew the watchdog of Culann and took its place","C":"He won a contest of speed against a chariot","D":"He retrieved a magical spear from the sea"},"answer":"B"},
  {"id":"hero-en-0684","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Prometheus stole fire from the gods to give to humans. What was his punishment?","options":{"A":"He was turned into a rock","B":"He was banished to the underworld","C":"He was chained to a rock and an eagle ate his liver daily","D":"He was blinded and forced to wander the earth"},"answer":"C"},
  {"id":"hero-en-0685","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'The Snow Queen' by Andersen, Gerda travels far to save her friend Kai. What has made Kai cold and unfeeling?","options":{"A":"A curse from the Snow Queen","B":"A splinter of a magic mirror in his eye and heart","C":"A potion given to him by a troll","D":"A spell from a wicked witch"},"answer":"B"},
  {"id":"hero-en-0686","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Orpheus travels to the underworld to bring back his wife Eurydice. Under what condition is he allowed to lead her out?","options":{"A":"He must not speak until they reach the surface","B":"He must not look back at her until they leave the underworld","C":"He must carry her the entire way","D":"He must reach the surface before dawn"},"answer":"B"},
  {"id":"hero-en-0687","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Gulliver's Travels' by Jonathan Swift, the tiny people who tie Gulliver down are called Lilliputians. What is the name of the land of giants he later visits?","options":{"A":"Laputa","B":"Brobdingnag","C":"Houyhnhnm","D":"Luggnagg"},"answer":"B"},
  {"id":"hero-en-0688","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Tintin's loyal dog is always by his side on adventures. What breed of dog is Milou (Snowy)?","options":{"A":"Beagle","B":"Jack Russell Terrier","C":"Fox Terrier","D":"West Highland Terrier"},"answer":"C"},
  {"id":"hero-en-0689","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Twenty Thousand Leagues Under the Sea', Professor Aronnax is a passenger aboard the Nautilus. What is his area of expertise?","options":{"A":"Marine biology","B":"Navigation","C":"Engineering","D":"Archaeology"},"answer":"A"},
  {"id":"hero-en-0690","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Asterix and his Gaulish village resist the Roman invaders. What magic potion gives the Gauls superhuman strength?","options":{"A":"A potion made from golden mistletoe","B":"A potion brewed by the druid Getafix","C":"A potion from the gods of the forest","D":"A potion traded from the Egyptians"},"answer":"B"},
  {"id":"hero-en-0691","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In Molière's play 'Le Bourgeois Gentilhomme', what social class does Monsieur Jourdain desperately want to belong to?","options":{"A":"The clergy","B":"The nobility","C":"The bourgeoisie","D":"The royal court"},"answer":"B"},
  {"id":"hero-en-0692","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Long John Silver, the pirate in 'Treasure Island', has a wooden leg. What is the name of his parrot?","options":{"A":"Jack","B":"Captain Flint","C":"Polly","D":"Roger"},"answer":"B"},
  {"id":"hero-en-0693","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Candide' by Voltaire, the young hero's tutor teaches him that everything happens for the best. What is the tutor's name?","options":{"A":"Cunégonde","B":"Martin","C":"Pangloss","D":"Cacambo"},"answer":"C"},
  {"id":"hero-en-0694","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"The hero Gilgamesh loses the plant of immortality he found at the bottom of the sea. Who steals it from him while he sleeps?","options":{"A":"The god Enlil","B":"A serpent","C":"Enkidu's ghost","D":"The ferryman Urshanabi"},"answer":"B"},
  {"id":"hero-en-0695","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Roland's famous sword in 'The Song of Roland' is said to be unbreakable. What is its name?","options":{"A":"Durandal","B":"Joyeuse","C":"Excalibur","D":"Curtana"},"answer":"A"},
  {"id":"hero-en-0696","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In the Mahabharata, the hero Arjuna hesitates to fight because his enemies include his own kinsmen. Who gives him philosophical guidance on the battlefield?","options":{"A":"Bhima","B":"Draupadi","C":"Yudhisthira","D":"Krishna"},"answer":"D"},
  {"id":"hero-en-0697","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'The Hunchback of Notre-Dame' by Victor Hugo, the bell-ringer Quasimodo is devoted to a gypsy dancer. What is her name?","options":{"A":"Fleur-de-Lys","B":"Esmeralda","C":"Gudule","D":"Phoebus"},"answer":"B"},
  {"id":"hero-en-0698","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Sun Wukong, the Monkey King, accompanies a monk on a pilgrimage to retrieve sacred scriptures. Where does the monk travel from China to?","options":{"A":"Japan","B":"Persia","C":"India","D":"Tibet"},"answer":"C"},
  {"id":"hero-en-0699","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In the Norse myth, Thor must disguise himself as a bride to retrieve his stolen hammer Mjöllnir. Who stole it?","options":{"A":"Loki","B":"Thrym the giant","C":"Jörmungandr","D":"Fenrir"},"answer":"B"},
  {"id":"hero-en-0700","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Maui, the demigod hero of Pacific mythology, slows the sun by lassoing it. What does he use as a lasso?","options":{"A":"A rope woven from coconut fibre","B":"His own enchanted hair","C":"His grandmother's jawbone","D":"A vine from the sky islands"},"answer":"C"},
  {"id":"hero-en-0701","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'The Count of Monte Cristo', Dantès adopts the title of 'Count of Monte Cristo'. Where does he find the treasure that funds his revenge?","options":{"A":"On the island of Elba","B":"On the island of Monte Cristo","C":"At the bottom of the sea near Marseille","D":"In a secret vault in Rome"},"answer":"B"},
  {"id":"hero-en-0702","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In Perrault's 'The Sleeping Beauty', how long does the princess sleep before being woken?","options":{"A":"Twenty-five years","B":"Fifty years","C":"One hundred years","D":"One thousand years"},"answer":"C"},
  {"id":"hero-en-0703","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Merlin, the wizard in Arthurian legend, guides young Arthur. What is unusual about Merlin's relationship with time?","options":{"A":"He can freeze time at will","B":"He ages backwards","C":"He can see only the past, not the future","D":"He lives outside of time entirely"},"answer":"B"},
  {"id":"hero-en-0704","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'The Phantom of the Opera', the Phantom is a musical genius who hides beneath the Paris opera house. What instrument does he master?","options":{"A":"The violin","B":"The organ","C":"The piano","D":"The cello"},"answer":"B"},
  {"id":"hero-en-0705","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"The hero Siegfried in Germanic legend is made invulnerable by bathing in dragon's blood. What prevents him from being fully protected?","options":{"A":"He forgets to cover his feet","B":"A leaf sticks to his shoulder during the bath","C":"He blinks at the wrong moment","D":"His cape blows away in the wind"},"answer":"B"},
  {"id":"hero-en-0706","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'The Twelve Dancing Princesses', a young man must discover where the princesses go each night. How does he manage to stay awake and follow them?","options":{"A":"He drinks a magic potion","B":"He pours the sleeping draught away and pretends to sleep","C":"He ties a string to the eldest princess","D":"He hides under one of their beds"},"answer":"B"},
  {"id":"hero-en-0707","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Ivan Tsarevich, a hero of Slavic tales, often rides a magical horse. What colour is this famous horse?","options":{"A":"Black","B":"White","C":"Golden","D":"Grey"},"answer":"C"},
  {"id":"hero-en-0708","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Le Petit Prince' by Antoine de Saint-Exupéry, the Little Prince comes from a very small planet. What does he tend on his planet?","options":{"A":"A golden apple tree","B":"A single rose","C":"A field of wheat","D":"A magical garden"},"answer":"B"},
  {"id":"hero-en-0709","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Cuchulainn, the great Irish hero, enters a battle frenzy called a 'riastrad'. What visible effect does this have on his body?","options":{"A":"He grows twice his normal size","B":"His body twists and distorts violently","C":"Flames surround him","D":"His hair turns white"},"answer":"B"},
  {"id":"hero-en-0710","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'The Song of Roland', Roland refuses to blow his horn Olifant to call for help until it is too late. Why does he hesitate so long?","options":{"A":"He fears the noise will scatter the enemy","B":"He does not want to appear weak or cowardly","C":"He believes Charlemagne is too far away to hear","D":"He has lost the horn in battle"},"answer":"B"},
  {"id":"hero-en-0711","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Which medieval hero of French literature fights a duel using the name 'the Black Knight', concealing his identity from his own king?","options":{"A":"Lancelot","B":"Gawain","C":"Ivanhoe","D":"Perceval"},"answer":"A"},
  {"id":"hero-en-0712","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Anansi the Spider is a trickster hero from West African folklore. What did Anansi buy from the Sky God to give stories to the world?","options":{"A":"A jar of wisdom","B":"All the world's stories","C":"The gift of song","D":"A magic web"},"answer":"B"},
  {"id":"hero-en-0713","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In Andersen's 'The Wild Swans', a princess must weave shirts from stinging nettles to free her brothers, who have been turned into swans. What is she forbidden to do during this task?","options":{"A":"Sleep or rest","B":"Speak or laugh","C":"Eat or drink","D":"Leave the forest"},"answer":"B"},
  {"id":"hero-en-0714","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In the original fairy tale, 'Riquet with the Tuft' (Riquet à la Houppe) is ugly but gifted with wit. What gift does he give to a beautiful but dull princess?","options":{"A":"The power of speech","B":"Intelligence","C":"Beauty","D":"Courage"},"answer":"B"},
  {"id":"hero-en-0715","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"The hero Aeneas escapes from the burning city of Troy carrying someone on his back. Who is it?","options":{"A":"His wife Creusa","B":"His father Anchises","C":"His son Ascanius","D":"His comrade Achates"},"answer":"B"},
  {"id":"hero-en-0716","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In Greek myth, Bellerophon tames the winged horse Pegasus to slay the Chimera. What is the Chimera?","options":{"A":"A creature with a lion's body and eagle's wings","B":"A monster with a lion's head, goat's body, and serpent's tail","C":"A dragon with three heads","D":"A bull-headed creature guarding a labyrinth"},"answer":"B"},
  {"id":"hero-en-0717","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Ali Baba and the Forty Thieves', the clever slave-girl Morgiana defeats the thieves' leader. How does she kill him during the final banquet?","options":{"A":"She poisons his wine","B":"She stabs him while performing a dance","C":"She pushes him into a well","D":"She locks him in the cave"},"answer":"B"},
  {"id":"hero-en-0718","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"The trickster hero Loki eventually turns against the gods and is punished. What is his punishment until Ragnarök?","options":{"A":"He is banished from Asgard","B":"He is bound under a mountain with a serpent dripping venom on him","C":"He is thrown into the void","D":"He is turned into a wolf"},"answer":"B"},
  {"id":"hero-en-0719","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In the hero monomyth described by Joseph Campbell, what is the name of the stage where the hero returns home with new wisdom?","options":{"A":"The call to adventure","B":"The road of trials","C":"The return with the elixir","D":"The revelation"},"answer":"C"},
  {"id":"hero-en-0720","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Pinocchio' by Carlo Collodi, Pinocchio is swallowed by a giant creature while searching for his creator Geppetto. What creature swallows them?","options":{"A":"A whale","B":"A giant shark","C":"A sea monster","D":"A giant catfish"},"answer":"B"},
  {"id":"hero-en-0721","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Lancelot is considered the greatest knight but fails the Grail quest. What is his fatal flaw?","options":{"A":"His lack of courage","B":"His adulterous love for Queen Guinevere","C":"His pride in battle","D":"His jealousy of other knights"},"answer":"B"},
  {"id":"hero-en-0722","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'The Little Match Girl' by Andersen, the girl lights her matches to stay warm on a cold New Year's Eve. What does she see in the last flame before she dies?","options":{"A":"Her mother","B":"Her deceased grandmother","C":"An angel","D":"A warm fireplace with a family"},"answer":"B"},
  {"id":"hero-en-0723","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"Hector, the greatest Trojan hero, is killed by Achilles to avenge the death of Achilles' closest companion. What is that companion's name?","options":{"A":"Ajax","B":"Patroclus","C":"Diomedes","D":"Nestor"},"answer":"B"},
  {"id":"hero-en-0724","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Sleeping Beauty', a curse is placed on the princess by an angry fairy because she was not invited to a celebration. What is the curse?","options":{"A":"She will never find love","B":"She will prick her finger on a spindle and die, or sleep until kissed","C":"She will remain a child forever","D":"She will be turned into a bird at midnight"},"answer":"B"},
  {"id":"hero-en-0725","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Cyrano de Bergerac', Cyrano secretly loves Roxane but helps his friend Christian win her instead. Why does Cyrano not confess his own love?","options":{"A":"He believes Roxane loves Christian","B":"He judges himself unworthy because of his large nose","C":"He has taken a vow of loyalty to Christian","D":"He is afraid of rejection"},"answer":"B"},
  {"id":"hero-en-0726","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In the Russian folklore tradition, the hero Ivan Tsarevich must often defeat Koschei the Deathless. Where is Koschei's death hidden?","options":{"A":"At the bottom of the sea","B":"Inside a needle, inside an egg, inside a duck, inside a chest, buried under an oak","C":"In a crystal bottle locked in a tower","D":"In his heart, which is kept in a magical box"},"answer":"B"},
  {"id":"hero-en-0727","category":"heroes","subcategory":None,"locale":"en","difficulty":"hard","question":"In 'Puss in Boots', the cat helps his master trick a king into believing he is a powerful marquis. What name does he give his master?","options":{"A":"The Marquis de Carabas","B":"The Count of Monte Cristo","C":"The Duke of Burgundy","D":"The Baron de Ferrières"},"answer":"A"},
]

PATH = Path(__file__).parent.parent / "src/data/questions/en/heroes.json"
with open(PATH) as f:
    data = json.load(f)

existing_ids = {q["id"] for q in data["questions"]}
existing_q = {q["question"].strip() for q in data["questions"]}

added = 0
skipped = []
for q in NEW_QUESTIONS:
    if q["id"] not in existing_ids and q["question"].strip() not in existing_q:
        data["questions"].append(q)
        added += 1
    else:
        skipped.append(q["id"])

print(f"Ajoutées: {added} | Ignorées: {len(skipped)} | Total: {len(data['questions'])}")
if skipped:
    print("Ignorées:", skipped[:10])

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write("\n")
